# [9665] BERTopic
Data file:
* https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9665/main/data/TeePublic_reviews_10k.csv

This extensive dataset, comprised of over 250,000 customer reviews, offers a detailed exploration of customer experiences on TeePublic, an online platform renowned for its diverse collection of fashion items. The dataset spans crucial information, including reviewer_id, store_location, latitude, longitude, date, month, year, title, review, and the review-label indicating a rating on a scale of 1 to 5.
  * reviewer_id: A unique identifier for each reviewer, ensuring anonymity and privacy.
  * store_location: Geographic information specifying the location of the TeePublic fashion store.
  * latitude: The latitude coordinate of the store's location, providing precise geospatial data.
  * longitude: The longitude coordinate of the store's location, offering detailed geographic insights.
  * date: The specific date when the review was posted, enabling temporal analysis.
  * month: The month in which the review was posted, facilitating monthly trends exploration.
  * year: The year of the review, allowing for yearly analysis and trend identification.
  * title: The title associated with each review, capturing succinct sentiments or key points.
  * review: The textual content of the review, presenting detailed feedback from customers.
  * review-label: The reviewer's rating on a scale from 1 to 5, providing a quantitative measure of satisfaction.

NOTE: Reduced to 10,000 reviews by professor

### Citation
```
@article{grootendorst2022bertopic,
  title={BERTopic: Neural topic modeling with a class-based TF-IDF procedure},
  author={Grootendorst, Maarten},
  journal={arXiv preprint arXiv:2203.05794},
  year={2022}
}
```

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 04/18/25 15:49:05

### Import libraries

In [2]:
%%time

! pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (3.4.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.5.7)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.14.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.51.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.30.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.1.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.13.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.5.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.1.31)
Downloading bertopic-0.17.0-py3-none-any.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.6/150.6 kB 2.7 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 29.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 18.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 28.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.1 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 57.7 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bertopic
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bertopic-0.17.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127
CPU times: user 984 ms, sys: 217 ms, total: 1.2 s
Wall time: 1min 58s

In [3]:
import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from bertopic import BERTopic

In [4]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

### Load data

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9665/main/data/TeePublic_reviews_10k.csv')
df.shape

(10000, 10)

### Examine data

In [6]:
df.head()

,reviewer_id,store_location,latitude,longitude,date,month,year,title,review,review-label
0,114649.0,US,37.09024,-95.712891,2022,2,2011 00:00:00,Love the magnets,"Love the magnets! They are thin but strong, an...",5
1,29288.0,US,37.09024,-95.712891,2022,12,2030 00:00:00,The process was simple and easy,"The process was simple and easy, shipping was ...",5
2,70483.0,US,37.09024,-95.712891,2022,8,2017 00:00:00,Account banned for no reason,I had my account banned for no good reason at ...,1
3,7180.0,US,37.09024,-95.712891,2023,5,2021 00:00:00,Excellent customer service,Excellent customer service. Quick and easy exc...,5
4,155554.0,US,37.09024,-95.712891,2021,4,2026 00:00:00,The shirts were awesome,The shirts were awesome! My sisters love the f...,5

### Prepare data

In [7]:
# Drop rows with missing values
df = df.dropna().reset_index(drop=True)
df.shape

(8887, 10)

In [8]:
df['combined_text'] = df['title'] + ' ' + df['review']
df.head()

,reviewer_id,store_location,latitude,longitude,date,month,year,title,review,review-label,combined_text
0,114649.0,US,37.09024,-95.712891,2022,2,2011 00:00:00,Love the magnets,"Love the magnets! They are thin but strong, an...",5,Love the magnets Love the magnets! They are th...
1,29288.0,US,37.09024,-95.712891,2022,12,2030 00:00:00,The process was simple and easy,"The process was simple and easy, shipping was ...",5,The process was simple and easy The process wa...
2,70483.0,US,37.09024,-95.712891,2022,8,2017 00:00:00,Account banned for no reason,I had my account banned for no good reason at ...,1,Account banned for no reason I had my account ...
3,7180.0,US,37.09024,-95.712891,2023,5,2021 00:00:00,Excellent customer service,Excellent customer service. Quick and easy exc...,5,Excellent customer service Excellent customer ...
4,155554.0,US,37.09024,-95.712891,2021,4,2026 00:00:00,The shirts were awesome,The shirts were awesome! My sisters love the f...,5,The shirts were awesome The shirts were awesom...

In [9]:
# Create function to clean text
lem = WordNetLemmatizer()
stop = set(stopwords.words('english'))
punct = string.punctuation

# Create function to clean_text
def clean_text(text):
    # print(f'{type(text)} : {text}')
    text = re.sub(r'\s+', ' ', text).translate(str.maketrans('', '', punct)).lower()
    tokens = text.split()
    tokens = [lem.lemmatize(word) for word in tokens if word not in stop]
    if len(tokens) > 2:
        return ' '.join(tokens)

# Perform necessary text preprocessing

In [10]:
%%time

# Clean combined_text column
df['clean_combined_text'] = df['combined_text'].apply(clean_text)

CPU times: user 7.59 s, sys: 237 ms, total: 7.83 s
Wall time: 11.9 s

In [11]:
# Drop rows with missing values
df = df.dropna().reset_index(drop=True)
df.shape

(8876, 12)

### Use BERTopic pretrained model

In [12]:
# To use the default model (all-MiniLM-L6-v2), you do not have to specify a model name
topic_model = BERTopic()

In [13]:
# Display default hyperparameters for model BERTopic
topic_model.get_params()

{'calculate_probabilities': False,
 'ctfidf_model': ClassTfidfTransformer(),
 'embedding_model': None,
 'hdbscan_model': HDBSCAN(min_cluster_size=10, prediction_data=True),
 'language': 'english',
 'low_memory': False,
 'min_topic_size': 10,
 'n_gram_range': (1, 1),
 'nr_topics': None,
 'representation_model': None,
 'seed_topic_list': None,
 'top_n_words': 10,
 'umap_model': UMAP(low_memory=False, metric='cosine', min_dist=0.0, n_components=5),
 'vectorizer_model': CountVectorizer(),
 'verbose': False,
 'zeroshot_min_similarity': 0.7,
 'zeroshot_topic_list': None}

In [14]:
%%time

# Train the BERTopic model on the cleaned combined text
topics, probs = topic_model.fit_transform(df['clean_combined_text'])

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

CPU times: user 5min 46s, sys: 6.53 s, total: 5min 52s
Wall time: 5min 50s

In [15]:
# Display topics
#  Topic_ID -1 : refers to outlier documents that do not fit well into any topics
#  Topic_ID 0 : groups together documents that have little meaning
#  Topic_ID 1 : the most frequent topic in the corpus
#  Topic_ID 2 and onwards : the 2nd, …, Nth most frequent topic in the corpus

topic_model.get_topics()

{-1: [('shirt', np.float64(0.010129930123621407)),
  ('quality', np.float64(0.009575383954318995)),
  ('design', np.float64(0.009184749954005856)),
  ('great', np.float64(0.008937834954504214)),
  ('good', np.float64(0.008163928227451841)),
  ('love', np.float64(0.007901653627270704)),
  ('tshirt', np.float64(0.007734781755366276)),
  ('order', np.float64(0.007538997333784741)),
  ('ordered', np.float64(0.0073776618157323295)),
  ('product', np.float64(0.007248034433018071))],
 0: [('size', np.float64(0.025315254864392657)),
  ('small', np.float64(0.023912309383887116)),
  ('shirt', np.float64(0.015024834175313674)),
  ('xl', np.float64(0.01444808498188088)),
  ('large', np.float64(0.013789504084448692)),
  ('ordered', np.float64(0.013581294557044226)),
  ('run', np.float64(0.013174788114769074)),
  ('medium', np.float64(0.012872629112101219)),
  ('sizing', np.float64(0.012486667654051587)),
  ('wrong', np.float64(0.012157339637221033))],
 1: [('shirt', np.float64(0.027387435739073776)),
  ('loved', np.float64(0.014917872944211602)),
  ('love', np.float64(0.013548031268732106)),
  ('happy', np.float64(0.013079362948142033)),
  ('arrived', np.float64(0.012086411428353752)),
  ('ordered', np.float64(0.01075253401727201)),
  ('and', np.float64(0.010636221380868203)),
  ('quality', np.float64(0.010570887691528356)),
  ('came', np.float64(0.010105672474757004)),
  ('good', np.float64(0.00916046167881006))],
 2: [('exactly', np.float64(0.02875468382049409)),
  ('item', np.float64(0.028533590420996537)),
  ('order', np.float64(0.027817666271930525)),
  ('product', np.float64(0.026675062120912044)),
  ('arrived', np.float64(0.025870917003808537)),
  ('time', np.float64(0.02538564454555794)),
  ('timely', np.float64(0.02295336818782815)),
  ('pleased', np.float64(0.022202350179098558)),
  ('received', np.float64(0.01934253319540097)),
  ('shipping', np.float64(0.019022844289908948))],
 3: [('hoodie', np.float64(0.12366540847177143)),
  ('hoodies', np.float64(0.04543401779587162)),
  ('hoody', np.float64(0.012440756002550712)),
  ('son', np.float64(0.011680667155418304)),
  ('love', np.float64(0.009922713976734663)),
  ('fit', np.float64(0.009864286534577514)),
  ('grandson', np.float64(0.009621530071356249)),
  ('quality', np.float64(0.009298093970233425)),
  ('size', np.float64(0.008832988210311045)),
  ('image', np.float64(0.00880346347789928))],
 4: [('package', np.float64(0.03221926753130566)),
  ('lost', np.float64(0.02558758219964787)),
  ('order', np.float64(0.02381488525006966)),
  ('item', np.float64(0.020447599799913903)),
  ('received', np.float64(0.01731595573181783)),
  ('sent', np.float64(0.015949313310704885)),
  ('email', np.float64(0.015878870648982798)),
  ('address', np.float64(0.015724516417089104)),
  ('christmas', np.float64(0.015276016209481985)),
  ('day', np.float64(0.015157317915878214))],
 5: [('mask', np.float64(0.15865481082218624)),
  ('face', np.float64(0.038762868581809086)),
  ('nose', np.float64(0.01591265819212947)),
  ('made', np.float64(0.011379464832403161)),
  ('would', np.float64(0.011136884853066274)),
  ('layer', np.float64(0.011133822296338485)),
  ('received', np.float64(0.010791827412550092)),
  ('wear', np.float64(0.01019480018120765)),
  ('different', np.float64(0.009567086075723125)),
  ('ordered', np.float64(0.009421298451291138))],
 6: [('sweatshirt', np.float64(0.16708426543813337)),
  ('hooded', np.float64(0.01219709614601144)),
  ('crewneck', np.float64(0.011575141845210163)),
  ('buffalo', np.float64(0.011575141845210163)),
  ('love', np.float64(0.01150041979304699)),
  ('ordered', np.float64(0.011468747095105066)),
  ('return', np.float64(0.011201283130053115)),
  ('daughter', np.float64(0.010663632141205647)),
  ('quality', np.float64(0.010450065701189146)),
  ('received', np.float64(0.009519653018294428))],
 7: [('tee', np.float64(0.11230240340660164)),
  ('public', np.float64(0.05080539810796591)),
  ('great', np.float64(0.022457638718087976)),
  ('soft', np.float64(0.01767330553266444)),
  ('super', np.float64(0.015354727223591023)),
  ('quality', np.float64(0.015075875157155388)),
  ('fit', np.float64(0.013579723416231078)),
  ('awesome', np.float64(0.013410427574920267)),
  ('love', np.float64(0.012470534512431632)),
  ('2nd', np.float64(0.012007726764594561))],
 8: [('tshirts', np.float64(0.06402783100529626)),
  ('tshirt', np.float64(0.05349846425783428)),
  ('happy', np.float64(0.020330707027765783)),
  ('comfortable', np.float64(0.01705254719319654)),
  ('design', np.float64(0.015331438643160564)),
  ('really', np.float64(0.01462708073894587)),
  ('love', np.float64(0.014460991594705342)),
  ('attractive', np.float64(0.014414449859479513)),
  ('quality', np.float64(0.01430826475020131)),
  ('many', np.float64(0.01380131601343017))],
 9: [('love', np.float64(0.09313008866193795)),
  ('shirt', np.float64(0.03986747926621276)),
  ('design', np.float64(0.023957962649979455)),
  ('loved', np.float64(0.019689340729544286)),
  ('absolutely', np.float64(0.017045597141664152)),
  ('guy', np.float64(0.016262022193165766)),
  ('material', np.float64(0.01595688887430579)),
  ('wilbur', np.float64(0.015122005697994306)),
  ('freakn', np.float64(0.015122005697994306)),
  ('dachshund', np.float64(0.015122005697994306))],
 10: [('teepublic', np.float64(0.08177837236743832)),
  ('always', np.float64(0.029295719397117607)),
  ('selection', np.float64(0.019867201469898118)),
  ('customer', np.float64(0.019466833436593042)),
  ('service', np.float64(0.018295376234803148)),
  ('rock', np.float64(0.015942193066540204)),
  ('great', np.float64(0.015844625539838845)),
  ('best', np.float64(0.01563120653644406)),
  ('satisfied', np.float64(0.015226833049349919)),
  ('easy', np.float64(0.014745751335431862))],
 11: [('artist', np.float64(0.10221472821956719)),
  ('artwork', np.float64(0.04863658060821972)),
  ('art', np.float64(0.03890665702874331)),
  ('independent', np.float64(0.03436016479434439)),
  ('great', np.float64(0.019985711346821405)),
  ('product', np.float64(0.019538614724479205)),
  ('selection', np.float64(0.019300570029691533)),
  ('work', np.float64(0.01759788386217862)),
  ('support', np.float64(0.01745971515325293)),
  ('amazing', np.float64(0.016431671212936823))],
 12: [('service', np.float64(0.0775890435654854)),
  ('excellent', np.float64(0.03914906112015039)),
  ('great', np.float64(0.03734861499039332)),
  ('customer', np.float64(0.028948939715240495)),
  ('shirt', np.float64(0.023320651784996645)),
  ('outstanding', np.float64(0.01997373416439526)),
  ('fast', np.float64(0.018525571020158844)),
  ('costumer', np.float64(0.01837976705737827)),
  ('company', np.float64(0.018242501073799343)),
  ('awesome', np.float64(0.01593033834053992))],
 13: [('fit', np.float64(0.07897306657573377)),
  ('true', np.float64(0.04193318959461813)),
  ('quality', np.float64(0.028712630257860562)),
  ('size', np.float64(0.02840000794315283)),
  ('comfy', np.float64(0.026940314220656035)),
  ('perfectly', np.float64(0.02680429002765292)),
  ('perfect', np.float64(0.022434604105991806)),
  ('great', np.float64(0.0220944424045879)),
  ('good', np.float64(0.021863112992429257)),
  ('advertised', np.float64(0.021743778747023122))],
 14: [('tshirt', np.float64(0.04175923537922148)),
  ('tshirts', np.float64(0.038625571829324024)),
  ('size', np.float64(0.03100221804531556)),
  ('large', np.float64(0.026916543273552515)),
  ('ordered', np.float64(0.020199633141129707)),
  ('small', np.float64(0.01897836924802821)),
  ('correct', np.float64(0.01891143303329949)),
  ('sent', np.float64(0.017835534495653515)),
  ('xl', np.float64(0.01621333350396467)),
  ('wrong', np.float64(0.015607257753436032))],
 15: [('delivery', np.float64(0.06184526675521524)),
  ('fast', np.float64(0.05003343986662071)),
  ('great', np.float64(0.044170568172985473)),
  ('shirt', np.float64(0.03849801490454473)),
  ('dope', np.float64(0.0381904019790397)),
  ('shipping', np.float64(0.031302390018237695)),
  ('price', np.float64(0.030096740446482306)),
  ('nice', np.float64(0.027266806709912855)),
  ('shirtquick', np.float64(0.023192298894333236)),
  ('awesome', np.float64(0.022946290459430557))],
 16: [('mug', np.float64(0.19844585061120468)),
  ('coffee', np.float64(0.10297693073377255)),
  ('cup', np.float64(0.0579985360396453)),
  ('broken', np.float64(0.05547962660639794)),
  ('travel', np.float64(0.027397186283920426)),
  ('arrived', np.float64(0.020265166325056573)),
  ('assbutt', np.float64(0.016915045667269406)),
  ('donor', np.float64(0.016915045667269406)),
  ('bubble', np.float64(0.016915045667269406)),
  ('packed', np.float64(0.016383074656431497))],
 17: [('customer', np.float64(0.08500322404114731)),
  ('service', np.float64(0.08477778289600954)),
  ('excellent', np.float64(0.03851924996956881)),
  ('product', np.float64(0.027279460154790894)),
  ('dependable', np.float64(0.02712719011610241)),
  ('hiccup', np.float64(0.024015812314881983)),
  ('company', np.float64(0.022844213056379355)),
  ('yeh', np.float64(0.02016267426399241)),
  ('great', np.float64(0.019692584101146215)),
  ('proactive', np.float64(0.018946882984659127))],
 18: [('teepublic', np.float64(0.05015549053693087)),
  ('favorite', np.float64(0.022659480200429242)),
  ('love', np.float64(0.02043477112226363)),
  ('find', np.float64(0.02007677334728703)),
  ('shopping', np.float64(0.019537579088813373)),
  ('tee', np.float64(0.019244308564981032)),
  ('recommend', np.float64(0.018380653391277414)),
  ('best', np.float64(0.017839737274654762)),
  ('variety', np.float64(0.017837100656915485)),
  ('like', np.float64(0.01695882012412669))],
 19: [('size', np.float64(0.07708190064320936)),
  ('wrong', np.float64(0.0745576747029459)),
  ('replaced', np.float64(0.031523618067922136)),
  ('ordered', np.float64(0.028743484259758836)),
  ('sent', np.float64(0.028400803440039448)),
  ('mistake', np.float64(0.02479740077320484)),
  ('ended', np.float64(0.023417437995298333)),
  ('immediately', np.float64(0.023329899109910963)),
  ('boo', np.float64(0.021533621713139696)),
  ('issue', np.float64(0.02015456908987375))],
 20: [('tee', np.float64(0.07881377532281765)),
  ('ah', np.float64(0.019987260931018446)),
  ('nephew', np.float64(0.01988225938125062)),
  ('special', np.float64(0.01699247264785585)),
  ('gift', np.float64(0.016693105003996216)),
  ('baby', np.float64(0.01588659581191613)),
  ('tees', np.float64(0.01588659581191613)),
  ('awesome', np.float64(0.015432410130529381)),
  ('image', np.float64(0.0154299850273858)),
  ('birthday', np.float64(0.0148573494304558))],
 21: [('soft', np.float64(0.1747946927843522)),
  ('comfortable', np.float64(0.06492899689633634)),
  ('super', np.float64(0.03314474720576234)),
  ('shirt', np.float64(0.03042392808745256)),
  ('material', np.float64(0.029403299476366523)),
  ('sarge', np.float64(0.022798541697485474)),
  ('design', np.float64(0.02079635467564199)),
  ('softness', np.float64(0.018103600454681835)),
  ('extra', np.float64(0.018054011952209428)),
  ('awesome', np.float64(0.018045367980998702))],
 22: [('gift', np.float64(0.1495982930136285)),
  ('christmas', np.float64(0.06676460716811142)),
  ('husband', np.float64(0.0376690273964341)),
  ('surprise', np.float64(0.02792332246330523)),
  ('present', np.float64(0.026733555312928575)),
  ('birthday', np.float64(0.02401008517174342)),
  ('bought', np.float64(0.02299551797178444)),
  ('mechanical', np.float64(0.022915257781260998)),
  ('collected', np.float64(0.022915257781260998)),
  ('framed', np.float64(0.022915257781260998))],
 23: [('tshirt', np.float64(0.04274794151148563)),
  ('tshirts', np.float64(0.034640552077439817)),
  ('service', np.float64(0.02787763385896964)),
  ('arrived', np.float64(0.022892176900329648)),
  ('customer', np.float64(0.02274136135710309)),
  ('within', np.float64(0.02156081106426196)),
  ('order', np.float64(0.019207211489745232)),
  ('shipped', np.float64(0.018895640838743236)),
  ('quickly', np.float64(0.01881371094779094)),
  ('time', np.float64(0.018389781878963698))],
 24: [('delivery', np.float64(0.17134623778348634)),
  ('quick', np.float64(0.12923442734401117)),
  ('fast', np.float64(0.06668139517773927)),
  ('product', np.float64(0.04646578123552618)),
  ('deliverygreat', np.float64(0.04449896571472656)),
  ('sauce', np.float64(0.034343583273194235)),
  ('accurate', np.float64(0.031795568436565176)),
  ('deliveryshirts', np.float64(0.030804277267389952)),
  ('efficient', np.float64(0.02970687523211664)),
  ('speedy', np.float64(0.028894827595832347))],
 25: [('service', np.float64(0.14949714063212952)),
  ('excellent', np.float64(0.05636653771981946)),
  ('good', np.float64(0.05489160550220064)),
  ('great', np.float64(0.051510088564267045)),
  ('product', np.float64(0.04056982107875246)),
  ('thnks', np.float64(0.040569006223017956)),
  ('platform', np.float64(0.03394551350364271)),
  ('amazing', np.float64(0.030651994198919782)),
  ('okay', np.float64(0.02392520836391193)),
  ('appreciated', np.float64(0.022460030307200368))],
 26: [('onesie', np.float64(0.07668242439853894)),
  ('granddaughter', np.float64(0.06331937240352915)),
  ('poo', np.float64(0.054079817433355624)),
  ('im', np.float64(0.04937499621207264)),
  ('son', np.float64(0.04094327765520973)),
  ('love', np.float64(0.03860855216237204)),
  ('dolphin', np.float64(0.03836668874233984)),
  ('greatbut', np.float64(0.03836668874233984)),
  ('knck', np.float64(0.03836668874233984)),
  ('treasure', np.float64(0.03836668874233984))],
 27: [('design', np.float64(0.12460336877086335)),
  ('beautiful', np.float64(0.059712431649856554)),
  ('amazing', np.float64(0.05210266614298175)),
  ('unique', np.float64(0.04772988766199459)),
  ('cool', np.float64(0.04447687252980294)),
  ('awesome', np.float64(0.04093695348350511)),
  ('excellent', np.float64(0.02939704409442265)),
  ('pleasure', np.float64(0.027610424010684816)),
  ('endless', np.float64(0.026370447666728764)),
  ('service', np.float64(0.024878609124803854))],
 28: [('shipping', np.float64(0.08836004583719546)),
  ('fast', np.float64(0.06131081837623999)),
  ('product', np.float64(0.057318333315479)),
  ('price', np.float64(0.055979254764687326)),
  ('great', np.float64(0.04089225372023729)),
  ('excellent', np.float64(0.03966267854009405)),
  ('purchase', np.float64(0.029535907438374195)),
  ('experience', np.float64(0.028527378390428383)),
  ('ship', np.float64(0.026654890963957345)),
  ('speedy', np.float64(0.02561877004528446))],
 29: [('shipping', np.float64(0.10604517129050846)),
  ('fast', np.float64(0.0719097630423453)),
  ('quick', np.float64(0.034868771310989095)),
  ('kinda', np.float64(0.02925424554342582)),
  ('advertized', np.float64(0.026848136314431868)),
  ('charge', np.float64(0.0243396812800975)),
  ('shirt', np.float64(0.023248175458626823)),
  ('shipment', np.float64(0.021470954973267432)),
  ('pricey', np.float64(0.021339866998417837)),
  ('shipped', np.float64(0.021157087215720485))],
 30: [('love', np.float64(0.08432107792262053)),
  ('shirt', np.float64(0.030594598903552903)),
  ('delivery', np.float64(0.02541241961057844)),
  ('loved', np.float64(0.021518934852720405)),
  ('super', np.float64(0.021297006659120748)),
  ('soft', np.float64(0.019610299819044465)),
  ('fast', np.float64(0.019312907788515597)),
  ('merchandise', np.float64(0.018648100888045475)),
  ('definitely', np.float64(0.01846246155211881)),
  ('ordering', np.float64(0.01831724141770194))],
 31: [('easy', np.float64(0.07760520352367734)),
  ('process', np.float64(0.03614052742651293)),
  ('simple', np.float64(0.027164141266878356)),
  ('order', np.float64(0.026402768199770794)),
  ('shipping', np.float64(0.020364139124224297)),
  ('shirt', np.float64(0.019097752124564858)),
  ('transaction', np.float64(0.017898176181888024)),
  ('ordering', np.float64(0.017150975110207807)),
  ('headache', np.float64(0.01676447073635324)),
  ('ordered', np.float64(0.016487218826483747))],
 32: [('tank', np.float64(0.22657471099905876)),
  ('top', np.float64(0.14559432012424886)),
  ('ive', np.float64(0.01874851937556776)),
  ('fit', np.float64(0.0187301873292686)),
  ('creed', np.float64(0.016024273341072728)),
  ('smokey', np.float64(0.016024273341072728)),
  ('assassin', np.float64(0.016024273341072728)),
  ('powell', np.float64(0.016024273341072728)),
  ('tanktop', np.float64(0.016024273341072728)),
  ('lake', np.float64(0.015058023947235058))],
 33: [('love', np.float64(0.07866719079093645)),
  ('tshirts', np.float64(0.07110132818061728)),
  ('tshirt', np.float64(0.06970623842946828)),
  ('duran', np.float64(0.05654681883356559)),
  ('trump', np.float64(0.042410114125174196)),
  ('tshirti', np.float64(0.03598292423909267)),
  ('hone', np.float64(0.031521927370467)),
  ('absolutely', np.float64(0.03045571481247036)),
  ('thanx', np.float64(0.02962118325770652)),
  ('gosh', np.float64(0.02962118325770652))],
 34: [('tshirt', np.float64(0.06461227832134443)),
  ('fit', np.float64(0.04764662247870453)),
  ('tshirts', np.float64(0.04715184402404041)),
  ('true', np.float64(0.03892222501777164)),
  ('size', np.float64(0.03308732128989096)),
  ('bought', np.float64(0.023599603382601895)),
  ('bandicoot', np.float64(0.02351723478076873)),
  ('crash', np.float64(0.02351723478076873)),
  ('sizing', np.float64(0.020295651119795297)),
  ('great', np.float64(0.018949370112740435))],
 35: [('loved', np.float64(0.07685333875971571)),
  ('son', np.float64(0.07520193855038522)),
  ('dad', np.float64(0.0632129970925584)),
  ('boy', np.float64(0.0400963887307251)),
  ('kid', np.float64(0.03573484420332944)),
  ('shirt', np.float64(0.029881022252741172)),
  ('gift', np.float64(0.029329073170286487)),
  ('liked', np.float64(0.029279489637774873)),
  ('eric', np.float64(0.02740477767309989)),
  ('gregg', np.float64(0.02740477767309989))],
 36: [('delivery', np.float64(0.11973701036026427)),
  ('quality', np.float64(0.08059054317069105)),
  ('good', np.float64(0.0712204236894842)),
  ('fast', np.float64(0.06476889807124134)),
  ('excellent', np.float64(0.031996172993014896)),
  ('quick', np.float64(0.02914589878382981)),
  ('great', np.float64(0.028989525101336736)),
  ('ton', np.float64(0.027601267460274328)),
  ('brilliant', np.float64(0.02494369963947693)),
  ('choice', np.float64(0.023979359428791255))],
 37: [('print', np.float64(0.1323110435318013)),
  ('screen', np.float64(0.08085486463460073)),
  ('printing', np.float64(0.05164704338429015)),
  ('low', np.float64(0.05038199388934253)),
  ('worst', np.float64(0.04438444926807468)),
  ('poor', np.float64(0.03953834541938653)),
  ('faded', np.float64(0.034336686678482456)),
  ('barely', np.float64(0.028866362078394665)),
  ('firm', np.float64(0.024282714393885973)),
  ('poorprint', np.float64(0.024282714393885973))],
 38: [('smell', np.float64(0.18274964150887593)),
  ('smelled', np.float64(0.05924690626818681)),
  ('vinegar', np.float64(0.05692667545114964)),
  ('strong', np.float64(0.031173012639146253)),
  ('bad', np.float64(0.029667981397075868)),
  ('wash', np.float64(0.02779973692575299)),
  ('like', np.float64(0.027546596444848772)),
  ('smelling', np.float64(0.025070114041952935)),
  ('slight', np.float64(0.024938410111317005)),
  ('odor', np.float64(0.0223231092113359))],
 39: [('easy', np.float64(0.23639677928852262)),
  ('ordering', np.float64(0.091665916581189)),
  ('order', np.float64(0.06658680006517222)),
  ('process', np.float64(0.05668778551299645)),
  ('coupled', np.float64(0.03506094271493197)),
  ('speedy', np.float64(0.029498374908539023)),
  ('platform', np.float64(0.02933672315850062)),
  ('peasy', np.float64(0.02933672315850062)),
  ('delivery', np.float64(0.027143576607548774)),
  ('system', np.float64(0.02532125813435461))],
 40: [('case', np.float64(0.2568175082941493)),
  ('phone', np.float64(0.1866299664601301)),
  ('cover', np.float64(0.04213320021897743)),
  ('iphone', np.float64(0.03781623991067338)),
  ('laptop', np.float64(0.03641882908311478)),
  ('cell', np.float64(0.028362179933005032)),
  ('3rd', np.float64(0.021584765157629724)),

In [16]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3855,-1_shirt_quality_design_great,"[shirt, quality, design, great, good, love, ts...",[service great got myï¿½ï¿½ï¿½ service great g...
1,0,816,0_size_small_shirt_xl,"[size, small, shirt, xl, large, ordered, run, ...",[shirt run small shirt run small menï¿½ï¿½ï¿½ï...
2,1,494,1_shirt_loved_love_happy,"[shirt, loved, love, happy, arrived, ordered, ...",[happy shirt iï¿½ï¿½ï¿½ happy shirt bought gre...
3,2,273,2_exactly_item_order_product,"[exactly, item, order, product, arrived, time,...",[order arrived time iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ...
4,3,201,3_hoodie_hoodies_hoody_son,"[hoodie, hoodies, hoody, son, love, fit, grand...",[love new hoodie love new hoodie definitely or...
...,...,...,...,...,...
85,84,12,84_issue_peep_service_customer,"[issue, peep, service, customer, corrected, fi...",[service great service great issue order custo...
86,85,12,85_teepublic_recommend_always_experience,"[teepublic, recommend, always, experience, bla...",[true review last purchase teepublic usual gre...
87,86,11,86_early_condition_came_arrived,"[early, condition, came, arrived, everything, ...",[received good condition timely received good ...
88,87,11,87_teepublic_from_second_item,"[teepublic, from, second, item, first, time, b...",[teepublic quick let know thatï¿½ï¿½ï¿½ teepub...
89,88,10,88_star_gave_four_a5,"[star, gave, four, a5, easilyhopefully, pricin...",[four star could five really like tshirt custo...

In [17]:
# Display topic sizes
#  topic_ID : # of documents assigned to topic
topic_model.topic_sizes_

Counter({61: 19,
         31: 42,
         72: 15,
         12: 74,
         -1: 3855,
         2: 273,
         0: 816,
         40: 33,
         20: 52,
         34: 39,
         6: 120,
         38: 37,
         7: 116,
         4: 161,
         58: 21,
         79: 13,
         29: 43,
         1: 494,
         11: 75,
         27: 44,
         18: 56,
         75: 14,
         28: 43,
         35: 38,
         74: 14,
         26: 44,
         70: 15,
         69: 15,
         9: 93,
         3: 201,
         48: 30,
         8: 116,
         50: 27,
         46: 32,
         57: 22,
         47: 30,
         55: 24,
         10: 83,
         19: 54,
         33: 39,
         24: 46,
         37: 38,
         52: 25,
         5: 145,
         41: 33,
         60: 19,
         42: 33,
         59: 20,
         22: 48,
         76: 14,
         23: 48,
         68: 17,
         45: 32,
         14: 63,
         17: 56,
         25: 45,
         21: 49,
         32: 42,
         88: 10,
         84: 12,
         44: 32,
         30: 42,
         54: 25,
         86: 11,
         43: 32,
         16: 59,
         62: 19,
         15: 61,
         13: 69,
         66: 18,
         39: 36,
         56: 23,
         83: 12,
         71: 15,
         80: 13,
         36: 38,
         64: 19,
         51: 27,
         65: 18,
         53: 25,
         67: 17,
         49: 28,
         78: 14,
         73: 14,
         63: 19,
         85: 12,
         82: 13,
         87: 11,
         77: 14,
         81: 13})

In [18]:
# Display list of words and their weights that comprise Topic 1
topic_model.get_topic(1)

[('shirt', np.float64(0.027387435739073776)),
 ('loved', np.float64(0.014917872944211602)),
 ('love', np.float64(0.013548031268732106)),
 ('happy', np.float64(0.013079362948142033)),
 ('arrived', np.float64(0.012086411428353752)),
 ('ordered', np.float64(0.01075253401727201)),
 ('and', np.float64(0.010636221380868203)),
 ('quality', np.float64(0.010570887691528356)),
 ('came', np.float64(0.010105672474757004)),
 ('good', np.float64(0.00916046167881006))]

In [19]:
# Display the embeddings for Topic 1
topic_model.topic_embeddings_[1]

array([-1.25511345e-02,  7.64826685e-02,  3.94381732e-02,  2.76250448e-02,
        2.75072977e-02, -3.97611149e-02,  5.45203174e-03,  1.09360022e-02,
       -2.50674412e-02,  7.28495093e-03,  4.74162251e-02, -3.23916525e-02,
        2.31039617e-02, -1.88894924e-02, -6.29254524e-03, -9.05061793e-03,
        2.38782652e-02, -6.21269736e-03, -7.89026543e-02, -6.06893450e-02,
       -2.41863355e-02, -2.72534452e-02, -6.80497335e-03,  1.42028779e-02,
       -5.13012633e-02, -4.32405956e-02, -5.09779081e-02,  5.58213284e-03,
       -8.42171069e-03, -4.52680551e-02, -2.38900185e-02,  7.15687424e-02,
        7.22024143e-02,  2.82762516e-02,  4.32896614e-03, -4.23753746e-02,
        2.41754521e-02, -8.59301724e-03,  3.84099851e-03,  1.52550600e-02,
       -1.23068793e-02, -5.50342835e-02, -2.29429156e-02, -1.16157637e-03,
       -5.31992614e-02,  1.69201344e-02, -6.52516726e-03,  6.96344674e-02,
       -1.50323911e-02,  5.49124181e-02, -1.37709212e-02, -2.91082375e-02,
       -3.38751040e-02, -1.74196530e-03, -2.29604659e-03,  5.22969142e-02,
       -2.07788888e-02, -9.06089693e-03, -2.50627324e-02, -4.16384265e-02,
       -4.91126953e-03, -1.34443445e-02, -5.06421775e-02, -3.61684640e-03,
        3.98108177e-02,  7.83394650e-03, -3.69295222e-03,  1.59079360e-03,
       -5.82682341e-02,  8.54128227e-03,  6.02372400e-02, -1.27724453e-03,
       -2.96211354e-02,  1.21800125e-01,  3.53551954e-02,  2.83019966e-03,
        4.58775871e-02, -1.79461576e-02, -2.96424646e-02,  6.72937855e-02,
       -1.07041098e-01,  9.32035968e-03, -4.92578791e-03, -3.06914514e-03,
       -2.57371902e-03,  3.03616002e-02, -3.20692058e-03, -1.26833506e-02,
        2.40537487e-02, -2.52928976e-02, -1.36443283e-02,  3.75387929e-02,
        1.14554083e-02, -7.45792594e-03,  1.20511297e-02,  1.48162330e-02,
        1.83045249e-02, -1.74095910e-02, -2.64733955e-02,  4.39672992e-02,
        3.62356454e-02,  3.11447550e-02,  5.51428199e-02,  1.51123367e-02,
        1.30137121e-02, -5.30023947e-02,  6.98413746e-03,  8.18143860e-02,
        5.79382218e-02, -1.53492333e-03, -2.99251657e-02,  7.18067074e-03,
       -8.87451321e-03,  5.49885165e-03,  7.95517582e-03, -1.45214209e-02,
        2.93805953e-02,  5.40485606e-02,  1.18959835e-02, -5.00281528e-02,
        5.46283880e-03,  4.58787829e-02, -3.15248556e-02, -4.51606587e-02,
       -7.31058791e-02, -8.72414000e-03,  6.64895251e-02,  6.21377187e-33,
       -5.59345596e-02,  3.64904068e-02,  3.12665856e-04,  3.12947901e-03,
        5.58902659e-02, -1.37011213e-02,  2.89538447e-02, -7.14645609e-02,
        1.05993878e-02,  3.54666635e-02, -3.76082100e-02,  2.70567238e-02,
       -1.56179862e-02,  6.33960590e-02,  1.25472285e-02,  2.41357018e-03,
       -5.93802519e-03, -1.33625511e-03, -9.31378901e-02,  1.44761731e-03,
       -1.74205587e-03,  4.78845090e-03,  3.67151424e-02, -1.41601730e-02,
       -7.51955155e-03, -1.69322379e-02,  3.63081805e-02,  1.69289876e-02,
        2.51379013e-02, -1.43338665e-02,  1.30505916e-02, -2.59743724e-02,
        5.71126714e-02, -4.34836671e-02, -3.85682099e-02, -3.63127626e-02,
       -1.72578450e-03, -3.15384343e-02,  4.06282507e-02, -6.16299501e-03,
        4.94066030e-02,  2.43140347e-02, -2.23404355e-02,  2.71222405e-02,
       -2.01224070e-02,  2.22202241e-02,  2.43759975e-02, -8.81706551e-03,
        2.57694796e-02, -2.59790774e-02, -2.66303830e-02,  2.78209057e-03,
        2.35628244e-02, -4.12984677e-02, -1.53932692e-02, -3.42700258e-02,
        2.69585922e-02, -1.70443077e-02, -3.59431729e-02, -9.26547777e-03,
        4.53105904e-02, -1.57794934e-02,  4.38120253e-02, -4.17721039e-03,
       -3.73956040e-02, -7.14480653e-02,  1.09600592e-02, -5.88224269e-02,
       -4.59891334e-02, -2.47693714e-02, -1.82530638e-02,  5.61132096e-02,
        6.13220967e-02,  1.99569389e-02,  2.54695937e-02, -7.53978966e-03,
       -1.34692555e-02,  3.95561717e-02, -1.31793693e-02, -2.82363836e-02,
        1.83599314e-03,  1.32669611e-02, -1.20408391e-03,  3.79078016e-02,
       -1.00097377e-02, -2.03951485e-02,  3.84661322e-03, -2.16303691e-02,
        3.06932954e-03,  2.72788689e-03,  7.02827750e-03,  2.96491440e-02,
        5.19549176e-02, -1.99473053e-02,  4.58433665e-02, -6.91347533e-33,
        1.36079062e-02,  2.84570009e-02,  8.74586497e-03,  2.22533215e-02,
        2.20756643e-02,  4.06692782e-03, -3.31525579e-02,  9.39179286e-02,
       -6.46342430e-03,  3.26380618e-02,  2.12766286e-02, -2.82384604e-02,
       -8.62906277e-02, -3.87871340e-02,  2.41586044e-02,  3.17603163e-02,
        1.27131835e-01, -1.58889301e-03, -1.00208735e-02, -3.82707007e-02,
        3.21827717e-02,  6.58042170e-03,  3.56615474e-03, -2.42727273e-03,
       -2.12591272e-02,  1.08598443e-02,  5.52622750e-02,  6.29232032e-03,
       -6.85651079e-02, -3.87919322e-02, -3.85500006e-02, -7.63376942e-03,
        8.43819603e-03,  1.27928764e-01,  5.71468659e-02, -4.44400422e-02,
       -3.08456318e-03,  5.33110388e-02,  1.37134001e-03,  1.52975172e-02,
        1.57485027e-02, -2.04875953e-02,  7.50238355e-03,  1.36387013e-02,
       -2.73852982e-02, -9.93626416e-02,  2.33374275e-02, -9.34568048e-02,
       -3.74997407e-02,  4.60441262e-02, -1.71256084e-02, -2.82306387e-03,
        1.25502041e-02, -2.76619457e-02, -3.13890129e-02,  2.04511061e-02,
       -1.21056885e-02,  3.40992510e-02, -4.69900714e-03,  1.39619028e-02,
       -3.37968990e-02, -6.81823771e-03, -2.48750448e-02, -3.56477797e-02,
        1.13411173e-02,  2.40694452e-02, -2.48651933e-02, -2.95472629e-02,
       -5.27837500e-02,  3.67245823e-02, -3.96347530e-02, -5.24731092e-02,
        4.72992007e-03, -2.17934907e-03, -6.50483072e-02, -6.33851737e-02,
       -2.55677998e-02,  7.51280561e-02, -3.33642736e-02,  3.30896862e-02,
        2.02002097e-02, -3.04575823e-02, -2.45452467e-02,  4.47618552e-02,
        1.42722223e-02,  1.51352072e-02,  1.63645018e-02,  6.72458252e-03,
       -7.92399794e-03,  4.09653299e-02, -1.86758004e-02,  1.89381298e-02,
        3.06033529e-02,  4.00258824e-02,  1.94518156e-02, -2.96549238e-08,
        1.19548514e-02, -2.67778542e-02,  5.03834942e-03,  5.12978323e-02,
        4.23679389e-02,  1.69580709e-02, -3.57888974e-02, -4.90319431e-02,
       -2.37399340e-02,  2.67469119e-02, -2.52871532e-02, -2.19547097e-03,
       -1.30292419e-02, -1.80831477e-02, -1.68736186e-02, -7.95787647e-02,
       -3.30457576e-02,  6.62769424e-03, -3.63812335e-02, -5.88035770e-02,
       -4.53758240e-02,  1.54388072e-02, -3.18787224e-03,  3.44662927e-02,
       -6.38659718e-03, -2.07978543e-02, -2.19821185e-02,  6.89220354e-02,
       -3.95915620e-02,  7.03383377e-03,  4.20644805e-02,  2.66939513e-02,
       -1.25565333e-02, -4.96638678e-02, -2.10946091e-02, -3.49160843e-02,
        1.24544930e-03, -4.77171466e-02,  3.18715088e-02, -6.73968196e-02,
       -1.98670253e-02, -2.54320167e-02,  1.53199490e-02,  1.70551054e-02,
        5.95318191e-02, -7.59680122e-02,  5.00209909e-03, -4.85814139e-02,
        3.17916344e-03, -3.10853380e-03,  2.64206827e-02, -4.81535457e-02,
        1.83064677e-03,  2.61342414e-02, -2.00467277e-02, -1.98931415e-02,
       -1.14476010e-02,  2.27705780e-02,  1.84317026e-02,  4.69918214e-02,
        2.82688346e-02, -6.07633889e-02, -2.32265629e-02, -6.94317091e-03],
      dtype=float32)

In [20]:
topic_model.get_document_info(df['clean_combined_text'])

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,love magnet love magnet thin strong like desig...,61,61_magnet_car_coolbut_lsu,"[magnet, car, coolbut, lsu, sticker, fastlove,...",[car magnet ordered college mascot magnet car ...,magnet - car - coolbut - lsu - sticker - fastl...,1.000000,True
1,process simple easy process simple easy shippi...,31,31_easy_process_simple_order,"[easy, process, simple, order, shipping, shirt...",[process simple easy process simple easy shipp...,easy - process - simple - order - shipping - s...,1.000000,True
2,account banned reason account banned good reas...,72,72_account_term_explanation_banned,"[account, term, explanation, banned, legal, wi...",[alleged violation unspecified term caused acc...,account - term - explanation - banned - legal ...,1.000000,False
3,excellent customer service excellent customer ...,12,12_service_excellent_great_customer,"[service, excellent, great, customer, shirt, o...",[great shirt great shirt great customer servic...,service - excellent - great - customer - shirt...,1.000000,False
4,shirt awesome shirt awesome sister love funny ...,-1,-1_shirt_quality_design_great,"[shirt, quality, design, great, good, love, ts...",[service great got myï¿½ï¿½ï¿½ service great g...,shirt - quality - design - great - good - love...,0.000000,False
...,...,...,...,...,...,...,...,...
8871,happy quick arrival ofï¿½ï¿½ï¿½ happy quick ar...,-1,-1_shirt_quality_design_great,"[shirt, quality, design, great, good, love, ts...",[service great got myï¿½ï¿½ï¿½ service great g...,shirt - quality - design - great - good - love...,0.000000,False
8872,great quality great quality fast delivery use ...,36,36_delivery_quality_good_fast,"[delivery, quality, good, fast, excellent, qui...","[good quality good quality fast delivery, good...",delivery - quality - good - fast - excellent -...,0.979244,False
8873,contacted legal regarding removalï¿½ï¿½ï¿½ con...,72,72_account_term_explanation_banned,"[account, term, explanation, banned, legal, wi...",[alleged violation unspecified term caused acc...,account - term - explanation - banned - legal ...,0.971839,False
8874,good shirt fantastic design huge selection goo...,-1,-1_shirt_quality_design_great,"[shirt, quality, design, great, good, love, ts...",[service great got myï¿½ï¿½ï¿½ service great g...,shirt - quality - design - great - good - love...,0.000000,False
8875,great customer service easyï¿½ï¿½ï¿½ great cus...,17,17_customer_service_excellent_product,"[customer, service, excellent, product, depend...",[customer service excellent theï¿½ï¿½ï¿½ custo...,customer - service - excellent - product - dep...,0.437900,False

In [21]:
# Display the representative docs for Topic 1
topic_model.get_representative_docs(1)

['happy shirt iï¿½ï¿½ï¿½ happy shirt bought great quality love design',
 'ordered 6 shirt arrivedï¿½ï¿½ï¿½ ordered 6 shirt arrived quickly look great',
 'shirt arrived good shippingï¿½ï¿½ï¿½ shirt arrived good shipping time design looked great son loved definitely recommend']

In [22]:
# Generates labels for each topic in a used-defined format
topic_model.generate_topic_labels(nr_words=4, separator='+')

['-1+shirt+quality+design+great',
 '0+size+small+shirt+xl',
 '1+shirt+loved+love+happy',
 '2+exactly+item+order+product',
 '3+hoodie+hoodies+hoody+son',
 '4+package+lost+order+item',
 '5+mask+face+nose+made',
 '6+sweatshirt+hooded+crewneck+buffalo',
 '7+tee+public+great+soft',
 '8+tshirts+tshirt+happy+comfortable',
 '9+love+shirt+design+loved',
 '10+teepublic+always+selection+customer',
 '11+artist+artwork+art+independent',
 '12+service+excellent+great+customer',
 '13+fit+true+quality+size',
 '14+tshirt+tshirts+size+large',
 '15+delivery+fast+great+shirt',
 '16+mug+coffee+cup+broken',
 '17+customer+service+excellent+product',
 '18+teepublic+favorite+love+find',
 '19+size+wrong+replaced+ordered',
 '20+tee+ah+nephew+special',
 '21+soft+comfortable+super+shirt',
 '22+gift+christmas+husband+surprise',
 '23+tshirt+tshirts+service+arrived',
 '24+delivery+quick+fast+product',
 '25+service+excellent+good+great',
 '26+onesie+granddaughter+poo+im',
 '27+design+beautiful+amazing+unique',
 '28+shipping+fast+product+price',
 '29+shipping+fast+quick+kinda',
 '30+love+shirt+delivery+loved',
 '31+easy+process+simple+order',
 '32+tank+top+ive+fit',
 '33+love+tshirts+tshirt+duran',
 '34+tshirt+fit+tshirts+true',
 '35+loved+son+dad+boy',
 '36+delivery+quality+good+fast',
 '37+print+screen+printing+low',
 '38+smell+smelled+vinegar+strong',
 '39+easy+ordering+order+process',
 '40+case+phone+cover+iphone',
 '41+shipping+fast+product+700',
 '42+print+printing+nice+clear',
 '43+teepublic+tshirts+tshirt+absolutely',
 '44+image+blurry+pixelated+print',
 '45+service+delivery+orderedrecieved+custmer',
 '46+tshirt+tshirts+nice+great',
 '47+thanks+great+shirt+look',
 '48+tee+funk+quilty+rb',
 '49+love+much+itmakes+loveit',
 '50+reliable+fast+service+efficient',
 '51+delivered+tshirts+tshirt+quickly',
 '52+product+excellent+great+futurekeep',
 '53+awesome+db+cooper+science',
 '54+print+printing+awsome+purchaser',
 '55+customer+service+unit+great',
 '56+tee+public+nice+prine',
 '57+quality+okay+completelysatisfied+demon',
 '58+sticker+513+aztec+coaster',
 '59+product+delivery+producttimely+excellent',
 '60+ink+printing+cheap+screen',
 '61+magnet+car+coolbut+lsu',
 '62+experience+experiencenothing+word+experiencelove',
 '63+quality+buck+price+great',
 '64+faded+graphic+shoe+look',
 '65+fabric+understated+material+really',
 '66+tshirt+tshirts+excellent+delivery',
 '67+shipping+fast+cool+awww',
 '68+communication+constant+communicated+good',
 '69+exactly+ordered+perfect+everything',
 '70+pealed+messed+wrinkled+money',
 '71+design+dor+exquisite+thisnwas',
 '72+account+term+explanation+banned',
 '73+product+service+great+wonderful',
 '74+pillow+lanka+sri+irish',
 '75+exchange+size+murray+aware',
 '76+selection+xtraxtra+subject+wonderful',
 '77+presented+design+good+live',
 '78+tshirt+african+print+tshirts',
 '79+woodstock+design+love+unique',
 '80+reluctant+cautious+confirm+online',
 '81+customer+exceptional+service+best',
 '82+envelope+service+friendly+rate',
 '83+graphic+tshirt+snowman+abominable',
 '84+issue+peep+service+customer',
 '85+teepublic+recommend+always+experience',
 '86+early+condition+came+arrived',
 '87+teepublic+from+second+item',
 '88+star+gave+four+a5']

In [23]:
# Visualize word bar chart for top 10 topics
topic_model.visualize_barchart(top_n_topics=10, n_words=4)

### Reduce topics to top N topics

In [24]:
bertopic_top_N = topic_model.reduce_topics(df['clean_combined_text'], nr_topics=5)

In [25]:
# Display reduced topics
bertopic_top_N.get_topics()

{-1: [('shirt', np.float64(0.07814171658639454)),
  ('great', np.float64(0.05663114358356436)),
  ('quality', np.float64(0.05516101069402389)),
  ('design', np.float64(0.040611102002803254)),
  ('love', np.float64(0.03847898482167635)),
  ('good', np.float64(0.035968061733018114)),
  ('ordered', np.float64(0.0347631887923937)),
  ('order', np.float64(0.03399811808765492)),
  ('product', np.float64(0.02863277439556132)),
  ('tshirt', np.float64(0.028414248467295785))],
 0: [('shirt', np.float64(0.07627819531008875)),
  ('great', np.float64(0.06228847907011604)),
  ('quality', np.float64(0.05018436589191344)),
  ('service', np.float64(0.0436643195168264)),
  ('love', np.float64(0.04304706171817738)),
  ('ordered', np.float64(0.0420477415683622)),
  ('size', np.float64(0.04064214608195645)),
  ('order', np.float64(0.038053331863740096)),
  ('good', np.float64(0.03356432713721314)),
  ('customer', np.float64(0.03154806878178811))],
 1: [('magnet', np.float64(0.8065494822169752)),
  ('car', np.float64(0.22117398710802075)),
  ('ordered', np.float64(0.1265177622550713)),
  ('sticker', np.float64(0.0973130388904905)),
  ('lsu', np.float64(0.06908917597127817)),
  ('coolbut', np.float64(0.06908917597127817)),
  ('fastlove', np.float64(0.06617240360365559)),
  ('perfect', np.float64(0.057676646021369335)),
  ('jeep', np.float64(0.05620124769512247)),
  ('product', np.float64(0.05612425080398102))],
 2: [('communication', np.float64(0.9320357261904538)),
  ('good', np.float64(0.2917209889411561)),
  ('process', np.float64(0.1418865771557808)),
  ('excellent', np.float64(0.12611990192088793)),
  ('update', np.float64(0.12318752606426442)),
  ('constant', np.float64(0.11571317225225339)),
  ('communicated', np.float64(0.11019801744729746)),
  ('talk', np.float64(0.10154878111680614)),
  ('delivery', np.float64(0.10047186642536073)),
  ('email', np.float64(0.09975388191997656))],
 3: [('account', np.float64(0.3138738255851989)),
  ('term', np.float64(0.12572299934261788)),
  ('explanation', np.float64(0.12136317743228053)),
  ('without', np.float64(0.08102179103532177)),
  ('banned', np.float64(0.07244159167744729)),
  ('legal', np.float64(0.07244159167744729)),
  ('use', np.float64(0.07005513562893502)),
  ('artist', np.float64(0.06307808776281063)),
  ('teepublic', np.float64(0.06280967065898177)),
  ('sold', np.float64(0.060217160407948306))]}

In [26]:
# Visualize word bar chart for reduced topics
bertopic_top_N.visualize_barchart(n_words=4)