# [9665] Latent Dirichlet Allocation 1

Data file:
* https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9665/main/data/Medium_articles.csv

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 02/23/25 19:52:51

### Import libraries

In [2]:
! pip install pyldavis

Collecting pyldavis
  Downloading pyLDAvis-3.4.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.24.2 in /usr/local/lib/python3.11/dist-packages (from pyldavis) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from pyldavis) (1.13.1)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pyldavis) (2.2.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from pyldavis) (1.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from pyldavis) (3.1.5)
Requirement already satisfied: numexpr in /usr/local/lib/python3.11/dist-packages (from pyldavis) (2.10.2)
Collecting funcy (from pyldavis)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from pyldavis) (1.6.1)
Requirement already satisfied: gensim in /usr/local/lib/python3.11/dist-packages (from pyldavis) (4.3.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from pyldavis) (75.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.0.0->pyldavis) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.0.0->pyldavis) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=2.0.0->pyldavis) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0.0->pyldavis) (3.5.0)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim->pyldavis) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->pyldavis) (3.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyldavis) (1.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim->pyldavis) (1.17.2)
Downloading pyLDAvis-3.4.1-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 15.8 MB/s eta 0:00:00
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Installing collected packages: funcy, pyldavis
Successfully installed funcy-2.0 pyldavis-3.4.1

In [3]:
import pandas as pd
import nltk
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer
from gensim.corpora import Dictionary
from gensim.models import LdaModel
from gensim.models.coherencemodel import CoherenceModel
import pyLDAvis
import pyLDAvis.gensim

import warnings
# Suppress the DeprecationWarning
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [4]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

### Load data

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9665/main/data/Medium_articles.csv')
df.shape

(337, 6)

### Review data

In [6]:
pd.set_option('max_colwidth', None)

In [7]:
df.head(2)

        author claps  reading_time  \
0   Justin Lee  8.3K            11
1  Conor Dewey  1.4K             7

                                                                                                                                            link  \
0                          https://medium.com/swlh/chatbots-were-the-next-big-thing-what-happened-5fc49dd6fa61?source=---------0----------------
1  https://towardsdatascience.com/python-for-data-science-8-concepts-you-may-have-forgotten-i-did-825966908393?source=---------1----------------

                                                                     title  \
0  Chatbots were the next big thing: what happened? – The Startup – Medium
1               Python for Data Science: 8 Concepts You May Have Forgotten

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text

In [8]:
# Create new column to perform LDA on
df['combined_text'] = df['title'] + ' ' + df['text']
df[['title', 'text', 'combined_text']].head(2)

                                                                     title  \
0  Chatbots were the next big thing: what happened? – The Startup – Medium
1               Python for Data Science: 8 Concepts You May Have Forgotten

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  \

### Preprocess data

In [9]:
# Save sample article index for later examination
SAMPLE_ARTICLE_1_IDX = 301

In [10]:
# Create preprocessing functions
def lemmatizer(text):
    return WordNetLemmatizer().lemmatize(text, pos='v')

def preprocess(text):
    result = []
    for token in simple_preprocess(text):
        if token not in STOPWORDS and len(token) > 3:
            result.append(lemmatizer(token))
    return result

In [11]:
# Show results of stemmer for sample document
example_doc = df.iloc[SAMPLE_ARTICLE_1_IDX]['combined_text']
print('original document:\n\t{}'.format(example_doc))
print('tokenized and lemmatized document:\n\t{}'.format(preprocess(example_doc)))

original document:
	Everything You Need to Know About Artificial Neural Networks The year 2015 was a monumental year in the field of artificial intelligence. Not only are computers learning more and learning faster, but we’re learning more about how to improve their systems. Everything is starting to align, and because of it we’re seeing strides we’ve never thought possible until now. We have programs that can tell stories about pictures. We have cars that are driving themselves. We even have programs that create art. If you want to read more about advancements in 2015, read this article. Here at Josh.ai, with AI technology becoming the core of just about everything we do, we think it’s important to understand some of the common terminology and to get a rough idea of how it all works.
A lot of the advances in artificial intelligence are new statistical models, but the overwhelming majority of the advances are in a technology called artificial neural networks (ANN). If you’ve read anything about them before, you’ll have read that these ANNs are a very rough model of how the human brain is structured. Take note that there is a difference between artificial neural networks and neural networks. Though most people drop the artificial for the sake of brevity, the word artificial was prepended to the phrase so that people in computational neurobiology could still use the term neural network to refer to their work. Below is a diagram of actual neurons and synapses in the brain compared to artificial ones.
Fear not if the diagram doesn’t come through very clearly. What’s important to understand here is that in our ANNs we have these units of calculation called neurons. These artificial neurons are connected by synapses which are really just weighted values. What this means is that given a number, a neuron will perform some sort of calculation (for example the sigmoid function), and then the result of this calculation will be multiplied by a weight as it “travels.” The weighted result can sometimes be the output of your neural network, or as I’ll talk about soon, you can have more neurons configured in layers, which is the basic concept to an idea that we call deep learning.
Artificial neural networks are not a new concept. In fact, we didn’t even always call them neural networks and they certainly don’t look the same now as they did at their inception. Back during the 1960s we had what was called a perceptron. Perceptrons were made of McCulloch-Pitts neurons. We even had biased perceptrons, and ultimately people started creating multilayer perceptrons, which is synonymous with the general artificial neural network we hear about now.
But wait, if we’ve had neural networks since the 1960s, why are they just now getting huge? It’s a long story, and I encourage you to listen to this podcast episode to listen to the “fathers” of modern ANNs talk about their perspective of the topic. To quickly summarize, there’s a hand full of factors that kept ANNs from becoming more popular. We didn’t have the computer processing power and we didn’t have the data to train them. Using them was frowned upon due to them having a seemingly arbitrary ability to perform well. Each one of these factors is changing. Our computers are getting faster and more powerful, and with the internet, we have all kinds of data being shared for use.
You see, I mentioned above that the neurons and synapses perform calculations. The question on your mind should be: “How do they learn what calculations to perform?” Was I right? The answer is that we need to essentially ask them a large amount of questions, and provide them with answers. This is a field called supervised learning. With enough examples of question-answer pairs, the calculations and values stored at each neuron and synapse are slowly adjusted. Usually this is through a process called backpropagation.
Imagine you’re walking down a sidewalk and you see a lamp post. You’ve never seen a lamp post before, so you walk right into it and say “ouch.” The next time you see a lamp post you scoot a few inches to the side and keep walking. This time your shoulder hits the lamp post and again you say “ouch.” The third time you see a lamp post, you move all the way over to ensure you don’t hit the lamp post. Except now something terrible has happened — now you’ve walked directly into the path of a mailbox, and you’ve never seen a mailbox before. You walk into it and the whole process happens again. Obviously, this is an oversimplification, but it is effectively what backpropogation does. An artificial neural network is given a multitude of examples and then it tries to get the same answer as the example given. When it is wrong, an error is calculated and the values at each neuron and synapse are propagated backwards through the ANN for the next time. This process takes a LOT of examples. For real world applications, the number of examples can be in the millions.
Now that we have an understanding of artificial neural networks and somewhat of an understanding in how they work, there’s another question that should be on your mind. How do we know how many neurons we need to use? And why did you bold the word layers earlier? Layers are just sets of neurons. We have an input layer which is the data we provide to the ANN. We have the hidden layers, which is where the magic happens. Lastly, we have the output layer, which is where the finished computations of the network are placed for us to use.
Layers themselves are just sets of neurons. In the early days of multilayer perceptrons, we originally thought that having just one input layer, one hidden layer, and one output layer was sufficient. It makes sense, right? Given some numbers, you just need one set of computations, and then you get an output. If your ANN wasn’t calculating the correct value, you just added more neurons to the single hidden layer. Eventually, we learned that in doing this we were really just creating a linear mapping from each input to the output. In other words, we learned that a certain input would always map to a certain output. We had no flexibility and really could only handle inputs we’d seen before. This was by no means what we wanted.
Now introduce deep learning, which is when we have more than one hidden layer. This is one of the reasons we have better ANNs now, because we need hundreds of nodes with tens if not more layers. This leads to a massive amount of variables that we need to keep track of at a time. Advances in parallel programming also allow us to run even larger ANNs in batches. Our artificial neural networks are now getting so large that we can no longer run a single epoch, which is an iteration through the entire network, at once. We need to do everything in batches which are just subsets of the entire network, and once we complete an entire epoch, then we apply the backpropagation.
Along with now using deep learning, it’s important to know that there are a multitude of different architectures of artificial neural networks. The typical ANN is setup in a way where each neuron is connected to every other neuron in the next layer. These are specifically called feed forward artificial neural networks (even though ANNs are generally all feed forward). We’ve learned that by connecting neurons to other neurons in certain patterns, we can get even better results in specific scenarios.
Recurrent Neural Networks (RNN) were created to address the flaw in artificial neural networks that didn’t make decisions based on previous knowledge. A typical ANN had learned to make decisions based on context in training, but once it was making decisions for use, the decisions were made independent of each other.
When would we want something like this? Well, think about playing a game of Blackjack. If you were given a 4 and a 5 to start, you know that 2 low cards are out of the deck. Information like this could help you determine whether or not you should hit. RNNs are very useful in natural language processing since prior words or characters are useful in understanding the context of another word. There are plenty of different implementations, but the intention is always the same. We want to retain information. We can achieve this through having bi-directional RNNs, or we can implement a recurrent hidden layer that gets modified with each feedforward. If you want to learn more about RNNs, check out either this tutorial where you implement an RNN in Python or this blog post where uses for an RNN are more thoroughly explained.
An honorable mention goes to Memory Networks. The concept is that we need to retain more information than what an RNN or LSTM keeps if we want to understand something like a movie or book where a lot of events might occur that build on each other.
Convolutional Neural Networks (CNN), sometimes called LeNets (named after Yann LeCun), are artificial neural networks where the connections between layers appear to be somewhat arbitrary. However, the reason for the synapses to be setup the way they are is to help reduce the number of parameters that need to be optimized. This is done by noting a certain symmetry in how the neurons are connected, and so you can essentially “re-use” neurons to have identical copies without necessarily needing the same number of synapses. CNNs are commonly used in working with images thanks to their ability to recognize patterns in surrounding pixels. There’s redundant information contained when you look at each individual pixel compared to its surrounding pixels, and you can actually compress some of this information thanks to their symmetrical properties. Sounds like the perfect situation for a CNN if you ask me. Christopher Olah has a great blog post about understanding CNNs as well as other types of ANNs which you can find here. Another great resource for understanding CNNs is this blog post.
The last ANN type that I’m going to talk about is the type called Reinforcement Learning. Reinforcement Learning is a generic term used for the behavior that computers exhibit when trying to maximize a certain reward, which means that it in itself isn’t an artificial neural network architecture. However, you can apply reinforcement learning or genetic algorithms to build an artificial neural network architecture that you might not have thought to use before. A great example and explanation can be found in this video, where YouTube user SethBling creates a reinforcement learning system that builds an artificial neural network architecture that plays a Mario game entirely on its own. Another successful example of reinforcement learning can be seen in this video where the company DeepMind was able to teach a program to master various Atari games.
Now you should have a basic understanding of what’s going on with the state of the art work in artificial intelligence. Neural networks are powering just about everything we do, including language translation, animal recognition, picture captioning, text summarization and just about anything else you can think of. You’re sure to hear more about them in the future so it’s good that you understand them now!
This post was written by Aaron at Josh.ai. Previously, Aaron worked at Northrop Grumman before joining the Josh team where he works on natural language programming (NLP) and artificial intelligence (AI). Aaron is a skilled YoYo expert, loves video games and music, has been programming since middle school and recently turned 21.
Josh.ai is an AI agent for your home. If you’re interested in following Josh and getting early access to the beta, enter your email at https://josh.ai.
Like Josh on Facebook — http://facebook.com/joshdotai
Follow Josh on Twitter — http://twitter.com/joshdotai
From a quick cheer to a standing ovation, clap to show how much you enjoyed this story.
Technology trends and New Invention? Follow this collection to update the latest trend! [UPDATE] As a collection editor, I don’t have any permission to add your articles in the wild. Please submit your article and I will approve. Also, follow this collection, please.

tokenized and lemmatized document:

In [12]:
%%time

# Preprocess all documents
processed_docs = df['combined_text'].map(preprocess)

CPU times: user 3.9 s, sys: 48.9 ms, total: 3.95 s
Wall time: 7.92 s

In [13]:
# Review first few processed documents
processed_docs.head()

0       [chatbots, thing, happen, startup, medium, headline, blare, chatbots, thing, hop, high, bright, eye, bushy, tail, industry, ripe, innovation, time, start, socialize, machine, wouldn, road, sign, point, insane, success, mobile, world, congress, chatbots, main, headliners, conference, organizers, cite, overwhelm, acceptance, event, inevitable, shift, focus, brand, corporates, chatbots, fact, significant, question, chatbots, monopolize, field, chatbots, place, year, answer, question, ecosystem, platform, dominate, chatbots, weren, technological, development, talk, grandiose, term, slump, spectacularly, hype, cycle, unfold, familiar, fashion, expectations, build, build, kind, fizzle, predict, paradim, shift, materialize, apps, tellingly, alive, look, breathless, optimism, turn, slightly, baffle, chatbot, revolution, promise, digit, ethan, bloch, sum, general, ...]
1                                      [python, data, science, concepts, forget, look, question, concept, syntax, program, constantly, unnatural, look, things, stackoverflow, resources, slow, good, raise, question, complete, understand, language, live, world, seemingly, infinite, accessible, free, resources, loom, search, away, time, bless, curse, manage, effectively, reliance, resources, build, poor, habit, long, term, personally, pull, code, similar, discussion, thread, time, take, time, learn, solidify, concept, reproduce, code, time, approach, lazy, path, resistance, short, term, ultimately, hurt, growth, productivity, ability, recall, syntax, cough, interview, line, recently, work, online, data, science, course, title, python, data, science, machine, learn, udemy, sound, like, youtube, early, lecture, series, remind, concepts, syntax, consistently, overlook, ...]
2                    [automate, feature, engineer, python, data, science, machine, learn, increasingly, move, hand, design, model, automatically, optimize, pipelines, tool, tpot, auto, sklearn, libraries, methods, random, search, simplify, model, selection, tune, part, machine, learn, find, best, model, dataset, little, manual, intervention, feature, engineer, arguably, valuable, aspect, machine, learn, pipeline, remain, entirely, human, labor, feature, engineer, know, feature, creation, process, construct, feature, exist, data, train, machine, learn, model, step, important, actual, model, machine, learn, algorithm, learn, data, create, feature, relevant, task, absolutely, crucial, excellent, paper, useful, things, know, machine, learn, typically, feature, engineer, draw, manual, process, rely, domain, knowledge, intuition, data, manipulation, process, extremely, ...]
3                                                       [machine, learn, zero, hero, freecodecamp, understand, machine, learn, question, mark, blog, post, gradually, increase, glue, inspirational, videos, friendly, text, relax, videos, time, inspire, continue, section, fair, article, earn, round, knowledge, passion, world, cool, move, paddle, pong, light, combos, street, fighter, revolve, programmer, functional, guess, behave, programmers, aren, gift, program, google, epic, game, fail, glitches, physics, experience, human, players, regardless, talent, teach, play, video, game, understand, language, identify, people, things, iceberg, skill, come, concept, recently, process, power, exist, outside, theory, talk, machine, learn, need, come, advance, algorithms, anymore, teach, come, advance, algorithm, like, work, algorithm, write, sort, breed, breed, analogy, watch, ...]
4    [reinforcement, learn, scratch, insight, data, want, learn, apply, artificial, intelligence, lead, practitioners, silicon, valley, york, toronto, learn, insight, artificial, intelligence, fellows, program, company, work, like, involve, insight, fellows, program, feel, free, touch, recently, give, talk, reilly, conference, beijing, interest, lessons, learn, world, lucky, attend, tutorial, deep, reinforcement, learn, deep, scratch, unity, technologies, think, session, arthur, juliani, extremely, informative, want, share, takeaways, conversations, company, see, rise, interest, deep, applications, tool, result, parallel, inner, workings, applications, deep, alphago, picture, esoteric, hard, understand, post, overview, core, aspects, field, understand, visuals, slide, talk, explanations, opinions, unclear, reach, deep, field, see, vast, amount, research, include, ...]
Name: combined_text, dtype: object

### Generate Gensim Dictionary object

In [14]:
%%time

# Map each word in ‘processed_docs’ to its unique integer id (index)
dictionary = Dictionary(processed_docs)

CPU times: user 445 ms, sys: 1.87 ms, total: 447 ms
Wall time: 1.18 s

In [15]:
print("{} words in Dictionary object".format(len(dictionary)))

14614 words in Dictionary object

In [16]:
# Display first 10 elements in dictionary
for i, (k, v) in enumerate(dictionary.items()):
    print(k, v)
    if i >= 10:
        break

0 able
1 abruptly
2 acceptance
3 access
4 accident
5 accord
6 achieve
7 adage
8 adopters
9 advantage
10 agenda

In [17]:
# Remove very rare and very common words
#  Filter out tokens that appear in
#   < 15 documents (absolute number) or
#   > 50% documents (fraction of total corpus size, not absolute number)
#  After the above two steps, keep only the first 10000 most frequent tokens
#   Next, shrink resulting gaps in word ids
dictionary.filter_extremes(no_below=15, no_above=0.5, keep_n=10000)
print("{} words remaining in Dictionary object".format(len(dictionary)))

1886 words remaining in Dictionary object

In [18]:
# Display first 10 elements in updated dictionary
for i, (k, v) in enumerate(dictionary.items()):
    print(k, v)
    if i >= 10:
        break

0 access
1 accord
2 achieve
3 advantage
4 aim
5 allow
6 alternative
7 analyze
8 answer
9 anticipate
10 apply

In [19]:
%%time

# Convert documents into the bag-of-words format: list of (token_id, token_count) 2-tuples
bow_corpus = [dictionary.doc2bow(doc) for doc in processed_docs]

CPU times: user 254 ms, sys: 2.06 ms, total: 256 ms
Wall time: 1.01 s

In [20]:
# Check processed BoW version of sample document
bow_corpus[SAMPLE_ARTICLE_1_IDX]

[(0, 1),
 (2, 1),
 (5, 1),
 (8, 4),
 (10, 2),
 (24, 2),
 (32, 2),
 (56, 1),
 (59, 1),
 (64, 3),
 (103, 2),
 (113, 1),
 (116, 1),
 (118, 1),
 (120, 2),
 (122, 1),
 (124, 4),
 (135, 2),
 (136, 1),
 (143, 2),
 (147, 2),
 (149, 1),
 (155, 2),
 (158, 1),
 (164, 3),
 (166, 3),
 (171, 5),
 (175, 1),
 (177, 1),
 (184, 1),
 (191, 5),
 (195, 4),
 (200, 1),
 (208, 3),
 (209, 1),
 (211, 16),
 (212, 1),
 (222, 1),
 (228, 1),
 (229, 1),
 (230, 1),
 (232, 1),
 (238, 1),
 (239, 2),
 (242, 1),
 (243, 2),
 (246, 1),
 (251, 2),
 (253, 1),
 (255, 1),
 (259, 1),
 (261, 6),
 (262, 1),
 (266, 2),
 (267, 1),
 (270, 2),
 (271, 1),
 (274, 2),
 (285, 2),
 (292, 4),
 (293, 1),
 (296, 2),
 (314, 1),
 (321, 5),
 (323, 1),
 (328, 2),
 (339, 1),
 (342, 1),
 (346, 1),
 (347, 1),
 (349, 1),
 (355, 1),
 (358, 1),
 (360, 1),
 (361, 3),
 (363, 1),
 (365, 3),
 (366, 1),
 (368, 2),
 (371, 1),
 (382, 2),
 (384, 1),
 (385, 3),
 (386, 2),
 (387, 1),
 (389, 1),
 (394, 1),
 (399, 5),
 (402, 1),
 (403, 2),
 (405, 2),
 (407, 1),
 (408, 1),
 (411, 3),
 (412, 23),
 (415, 1),
 (416, 1),
 (422, 1),
 (423, 2),
 (424, 3),
 (437, 1),
 (438, 1),
 (439, 1),
 (443, 1),
 (450, 1),
 (452, 2),
 (456, 3),
 (457, 1),
 (461, 1),
 (467, 1),
 (473, 2),
 (479, 1),
 (480, 1),
 (481, 4),
 (485, 1),
 (488, 6),
 (491, 1),
 (495, 1),
 (505, 1),
 (510, 1),
 (517, 2),
 (518, 1),
 (519, 1),
 (522, 1),
 (525, 1),
 (534, 1),
 (537, 1),
 (538, 4),
 (539, 3),
 (543, 1),
 (547, 1),
 (548, 1),
 (550, 3),
 (553, 1),
 (559, 2),
 (565, 3),
 (569, 1),
 (587, 1),
 (601, 1),
 (605, 1),
 (607, 1),
 (615, 1),
 (619, 1),
 (625, 1),
 (630, 1),
 (639, 1),
 (643, 1),
 (651, 1),
 (658, 2),
 (665, 1),
 (668, 1),
 (672, 2),
 (675, 1),
 (678, 1),
 (679, 5),
 (684, 1),
 (694, 3),
 (700, 4),
 (712, 4),
 (717, 2),
 (731, 14),
 (735, 1),
 (762, 1),
 (765, 2),
 (776, 3),
 (782, 1),
 (783, 1),
 (788, 1),
 (790, 3),
 (793, 1),
 (796, 2),
 (799, 1),
 (807, 1),
 (808, 1),
 (815, 1),
 (816, 1),
 (820, 1),
 (825, 3),
 (829, 1),
 (835, 2),
 (846, 1),
 (851, 1),
 (856, 1),
 (859, 1),
 (863, 1),
 (864, 1),
 (871, 1),
 (876, 1),
 (880, 1),
 (885, 5),
 (887, 1),
 (902, 2),
 (907, 1),
 (909, 2),
 (926, 1),
 (929, 2),
 (930, 1),
 (936, 5),
 (941, 1),
 (943, 3),
 (948, 2),
 (961, 2),
 (968, 1),
 (976, 2),
 (984, 1),
 (985, 1),
 (986, 2),
 (987, 1),
 (996, 2),
 (1009, 1),
 (1011, 1),
 (1016, 1),
 (1017, 2),
 (1019, 1),
 (1020, 2),
 (1022, 1),
 (1025, 1),
 (1030, 1),
 (1038, 2),
 (1065, 1),
 (1095, 1),
 (1102, 1),
 (1104, 2),
 (1119, 1),
 (1121, 1),
 (1127, 1),
 (1141, 1),
 (1152, 1),
 (1173, 1),
 (1183, 1),
 (1186, 1),
 (1188, 1),
 (1194, 1),
 (1197, 1),
 (1204, 1),
 (1209, 1),
 (1220, 1),
 (1242, 1),
 (1246, 2),
 (1247, 1),
 (1250, 3),
 (1256, 2),
 (1278, 1),
 (1283, 1),
 (1295, 1),
 (1314, 1),
 (1316, 2),
 (1317, 1),
 (1323, 1),
 (1331, 1),
 (1332, 2),
 (1343, 1),
 (1346, 1),
 (1364, 1),
 (1377, 2),
 (1381, 1),
 (1412, 1),
 (1420, 1),
 (1437, 1),
 (1438, 1),
 (1444, 1),
 (1449, 1),
 (1454, 1),
 (1479, 2),
 (1503, 1),
 (1561, 1),
 (1566, 3),
 (1567, 1),
 (1576, 1),
 (1592, 4),
 (1596, 1),
 (1620, 1),
 (1637, 3),
 (1639, 1),
 (1655, 1),
 (1658, 1),
 (1668, 1),
 (1686, 1),
 (1707, 1),
 (1720, 1),
 (1733, 1),
 (1747, 1),
 (1748, 2),
 (1751, 1),
 (1762, 1),
 (1763, 1),
 (1768, 5),
 (1773, 1),
 (1780, 1),
 (1802, 1),
 (1832, 1),
 (1847, 1),
 (1857, 1)]

In [21]:
# Review sample document in B0W format
bow_example_doc = bow_corpus[SAMPLE_ARTICLE_1_IDX]

print('word_index\tword\t\tword_occurences')
for i in range(len(bow_example_doc)):
    print(f'{bow_example_doc[i][0]}\t\t{dictionary[bow_example_doc[i][0]]}\t\t{bow_example_doc[i][1]}')

word_index	word		word_occurences
0		access		1
2		achieve		1
5		allow		1
8		answer		4
10		apply		2
24		basic		2
32		brain		2
56		company		1
59		complete		1
64		computers		3
103		early		2
113		email		1
116		entirely		1
118		error		1
120		essentially		2
122		eventually		1
124		examples		4
135		facebook		2
136		fact		1
143		faster		2
147		field		2
149		finish		1
155		forward		2
158		general		1
164		happen		3
166		have		3
171		hide		5
175		home		1
177		https		1
184		imagine		1
191		information		5
195		intelligence		4
200		internet		1
208		language		3
209		larger		1
211		layer		16
212		lead		1
222		linear		1
228		long		1
229		longer		1
230		love		1
232		majority		1
238		memory		1
239		mention		2
242		middle		1
243		mind		2
246		modern		1
251		natural		2
253		necessarily		1
255		obviously		1
259		originally		1
261		output		6
262		overwhelm		1
266		picture		2
267		place		1
270		play		2
271		plenty		1
274		power		2
285		provide		2
292		question		4
293		quickly		1
296		reason		2
314		sake		1
321		see		5
323		sense		1
328		setup		2
339		soon		1
342		specific		1
346		state		1
347		statistical		1
349		stories		1
355		successful		1
358		sure		1
360		systems		1
361		talk		3
363		team		1
365		technology		3
366		tell		1
368		term		2
371		text		1
382		try		2
384		turn		1
385		type		3
386		useful		2
387		user		1
389		usually		1
394		wait		1
399		word		5
402		wrong		1
403		year		2
405		ability		2
407		actually		1
408		address		1
411		article		3
412		artificial		23
415		certainly		1
416		check		1
422		common		1
423		compare		2
424		concept		3
437		drive		1
438		drop		1
439		effectively		1
443		explain		1
450		function		1
452		hear		2
456		important		3
457		include		1
461		join		1
467		map		1
473		note		2
479		pair		1
480		path		1
481		perform		4
485		powerful		1
488		program		6
491		python		1
495		recently		1
505		seemingly		1
510		share		1
517		somewhat		2
518		sort		1
519		sound		1
522		specifically		1
525		store		1
534		track		1
537		ultimately		1
538		value		4
539		video		3
543		youtube		1
547		actual		1
548		add		1
550		advance		3
553		appear		1
559		calculate		2
565		collection		3
569		contain		1
587		encourage		1
601		future		1
605		hand		1
607		hundreds		1
615		knowledge		1
619		master		1
625		name		1
630		optimize		1
639		previous		1
643		real		1
651		resource		1
658		single		2
665		structure		1
668		topic		1
672		twitter		2
675		use		1
678		variables		1
679		walk		5
684		algorithms		1
694		blog		3
700		connect		4
712		game		4
717		idea		2
731		neurons		14
735		perfect		1
762		teach		1
765		thank		2
776		weight		3
782		adjust		1
783		agent		1
788		applications		1
790		architecture		3
793		atari		1
796		batch		2
799		cars		1
807		convolutional		1
808		core		1
815		determine		1
816		difference		1
820		directly		1
825		entire		3
829		episode		1
835		factor		2
846		image		1
851		introduce		1
856		maximize		1
859		millions		1
863		ones		1
864		parallel		1
871		popular		1
876		previously		1
880		propagate		1
885		reinforcement		5
887		reward		1
902		surround		2
907		tutorial		1
909		update		2
926		architectures		1
929		backpropagation		2
930		bias		1
936		certain		5
941		clearly		1
943		cnns		3
948		context		2
961		diagram		2
968		earlier		1
976		fee		2
984		huge		1
985		identical		1
986		implement		2
987		improve		1
996		large		2
1009		modify		1
1011		nod		1
1016		parameters		1
1017		pattern		2
1019		pixel		1
1020		pixels		2
1022		possible		1
1025		prior		1
1030		reduce		1
1038		rough		2
1065		card		1
1095		recognize		1
1102		supervise		1
1104		trend		2
1119		individual		1
1121		lastly		1
1127		scenarios		1
1141		commonly		1
1152		occur		1
1173		book		1
1183		correct		1
1186		days		1
1188		deepmind		1
1194		enter		1
1197		events		1
1204		generally		1
1209		implementations		1
1220		kinds		1
1242		perspective		1
1246		recurrent		2
1247		refer		1
1250		rnns		3
1256		set		2
1278		ensure		1
1283		lstm		1
1295		translation		1
1314		generic		1
1316		http		2
1317		independent		1
1323		phrase		1
1331		summarize		1
1332		typical		2
1343		character		1
1346		connections		1
1364		handle		1
1377		listen		2
1381		massive		1
1412		wasn		1
1420		backwards		1
1437		expert		1
1438		explanation		1
1444		magic		1
1449		recognition		1
1454		situation		1
1479		keep		2
1503		configure		1
1561		slowly		1
1566		calculations		3
1567		copy		1
1576		multiply		1
1592		decisions		4
1596		editor		1
1620		school		1
1637		calculation		3
1639		computational		1
1655		fear		1
1658		genetic		1
1668		music		1
1686		sufficient		1
1707		latest		1
1720		movie		1
1733		travel		1
1747		align		1
1748		arbitrary		2
1751		behavior		1
1762		exhibit		1
1763		flexibility		1
1768		neuron		5
1773		properties		1
1780		submit		1
1802		units		1
1832		iteration		1
1847		wild		1
1857		sigmoid		1

### Train LDA model

In [22]:
%%time

lda_model = LdaModel(corpus=bow_corpus, id2word=dictionary, num_topics=10,
                     chunksize=10, passes=10, alpha='auto', eta='auto',
                     gamma_threshold=0.001, per_word_topics=True, random_state=42)

CPU times: user 6.76 s, sys: 73.8 ms, total: 6.84 s
Wall time: 16.7 s

### Evaluate LDA model

In [23]:
%%time

# Compute Coherence Score: c_v
coherence_model_lda = CoherenceModel(model=lda_model, texts=processed_docs,
                                     dictionary=dictionary, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('Coherence Score: ', coherence_lda)

Coherence Score:  0.47228836260580176
CPU times: user 9.91 s, sys: 142 ms, total: 10.1 s
Wall time: 10.3 s

In [24]:
%%time

# Compute Coherence Score: u_mass
coherence_model_lda = CoherenceModel(model=lda_model, texts=processed_docs,
                                     dictionary=dictionary, coherence='u_mass')
coherence_lda = coherence_model_lda.get_coherence()
print('Coherence Score: ', coherence_lda)

Coherence Score:  -1.0977017868328844
CPU times: user 155 ms, sys: 126 µs, total: 156 ms
Wall time: 156 ms

In [25]:
# Get the gamma matrix (document-topic matrix)
gamma, _ = lda_model.inference(bow_corpus)

# Display the gamma values
for i, gamma_values in enumerate(gamma):
    print(f"Document {i+1}: {gamma_values}")

Document 1: [1.2199944e+01 9.2726761e+01 1.3182793e+02 1.8802855e+02 1.8803070e+02
 9.1095352e-01 1.7024544e+01 7.7462912e+00 2.1276281e+00 1.2470807e-01]
Document 2: [91.58197   24.551872  61.479774   0.3270069 27.398998  83.69977
 16.345642  41.429535  24.881004   0.1247493]
Document 3: [190.64886     44.028126    25.464064     0.28611803  84.50818
  62.825123   137.60521     53.927326    24.973427     1.463624  ]
Document 4: [  2.1672626   2.9529145 117.42148     5.7219043  67.516396   61.043873
   1.7238411  33.32842    17.658821    7.29273  ]
Document 5: [180.70508   29.322933  39.668633   4.322441  68.96046    8.427811
  37.657352  16.07118    7.818147 295.72717 ]
Document 6: [1.57757294e+02 5.45648232e+01 9.39603806e+00 3.10409129e-01
 2.30033836e+01 7.36554480e+00 5.79392883e+02 3.35479469e+01
 1.11156158e+02 1.24625415e-01]
Document 7: [ 8.254444 34.157276 43.85752  29.44574  37.643715 12.031549 33.688515
 47.253075 42.267426 21.225203]
Document 8: [9.03857422e+00 5.91074610e+00 1.02845306e+01 2.89707661e-01
 7.16426697e+01 4.68060379e+01 1.27366447e+00 1.49522766e+02
 6.95846367e+00 1.24656126e-01]
Document 9: [2.5513527e+02 1.5039052e+00 4.9821353e+00 8.3216267e+00 1.5652049e+01
 4.7698755e+00 1.0599170e+00 8.5433674e-01 4.5969445e-01 1.2461976e-01]
Document 10: [2.6354149e+01 2.4138403e+00 8.8517303e+01 5.4922138e+01 4.6194458e+01
 8.7346970e+01 7.9806304e+00 4.1439468e+02 4.1473614e+01 1.2483778e-01]
Document 11: [ 3.424749    8.759166   73.21937     0.28720123 37.36056    12.046694
  4.239372   98.93374     0.5579537  12.031424  ]
Document 12: [181.33769    84.0459     85.714035    0.2854952   9.072504   52.637924
   1.3280388   1.7945924   0.497213    5.0898685]
Document 13: [ 61.057255  15.267976 306.14688   31.744728 213.94559   25.522089
  16.711716  43.9697    11.346353  20.001255]
Document 14: [1.7241932e+01 4.1971378e+00 3.9339276e+02 3.3817509e-01 4.1722393e+00
 6.0559345e+01 1.8141990e+00 5.4630651e+00 2.6429123e+02 8.2675095e+00]
Document 15: [2.8556974e+00 1.8795203e+00 2.0730334e+02 2.8986788e-01 1.1238385e+00
 4.7206960e+00 4.5947397e+02 1.1135706e+00 6.3845921e+01 1.2479710e-01]
Document 16: [  3.1528518    1.7907475  200.20767      0.96974033   1.7738099
  18.57263    402.7368       0.84584177  22.032606     8.620533  ]
Document 17: [ 28.48627     5.9204    127.586235   49.849747   18.364475   21.16452
   8.045216  432.43268     8.278434    1.5358384]
Document 18: [6.1542673e+00 1.8064433e+00 2.1764429e+02 1.3267772e+01 3.1056106e+00
 7.3155522e+00 1.1336095e+00 8.4516394e-01 4.6870971e-01 1.2468897e-01]
Document 19: [1.7818568e+00 5.4183025e+00 5.0535809e+02 3.0575645e-01 3.9554126e+00
 6.7329040e+00 2.1349407e+01 2.7438092e+00 1.1902303e+02 9.1161194e+00]
Document 20: [1.6822269e+00 1.4416214e+00 1.0172716e+02 2.9968336e-01 2.1192017e+01
 1.2412533e+03 1.7682943e+00 1.4849286e+02 5.6954277e-01 1.2475633e-01]
Document 21: [6.3878582e+01 7.3679398e+01 2.0942285e+02 1.3584387e+00 7.5029779e+02
 2.4974294e+00 1.6488605e+01 1.0154073e+01 5.8205628e-01 1.2474206e-01]
Document 22: [30.784618  28.79935   55.287266   0.2830736 14.767353  36.92208
  1.2941813  6.71931   26.514547   7.4705925]
Document 23: [5.2716331e+00 4.0814049e+01 1.8106065e+02 6.2343990e+01 1.1099038e+02
 8.7896938e+00 2.1741941e+01 1.3966481e+01 1.6534271e+00 1.2465565e-01]
Document 24: [1.1441091  1.950543   2.0713305  3.202861   0.74992424 1.0341842
 0.96056515 0.6158956  1.0557177  0.12458151]
Document 25: [ 41.633034   231.98477     74.67319      2.2007947   43.816425
  25.88574      4.8846984  119.78645      0.76730084   6.0772057 ]
Document 26: [5.18198433e+01 2.54649277e+02 9.09794540e+01 2.86435872e-01
 4.87849808e+01 6.41639709e+01 4.27116623e+01 9.19558563e+01
 1.31937284e+01 1.24875784e-01]
Document 27: [8.4185478e+01 1.3450584e+02 6.0850250e+01 2.0427897e+00 9.1837378e+00
 1.5473877e+01 2.0840168e+01 4.0818810e+00 5.2287477e-01 1.2472360e-01]
Document 28: [589.36896  206.3666   361.75665   19.432629 463.38123   14.376457
  50.428368  98.16578    4.64417  130.25116 ]
Document 29: [ 14.486725   218.73611    101.4814     478.83032    131.61026
  27.959042     9.350014     5.701313     0.47910315  17.956602  ]
Document 30: [ 40.343773  310.29443    86.05308    17.167795  103.62913    21.873728
  10.264961  134.11668     0.8140123  19.141136 ]
Document 31: [46.60036    54.978      73.16965     0.28384745 65.00173     2.0369933
  9.6695385   0.9066601  81.05968     0.12465797]
Document 32: [23.43422    41.781113   32.4659      0.27834192 15.92666     1.754483
 29.715897   72.59378    31.772953    0.12462974]
Document 33: [2.1414345e+01 4.1585228e+01 9.4898758e+01 3.3141056e+01 2.0642497e+02
 1.1641585e+01 4.1649799e+01 2.8357826e+01 2.5247180e+00 1.2478468e-01]
Document 34: [121.6654     52.776276   51.114555   35.25019     1.2838719   5.8986945
  17.13154     6.279236   26.664848    8.742688 ]
Document 35: [34.858036   3.0787206 20.66438    0.3063213  2.4394617  6.1992283
 53.52783    2.5601668  0.5421575  1.7090045]
Document 36: [76.46365    27.216616   74.10672     0.27937958  3.8249328   5.7801604
 13.4856205   7.9753857   8.590828    0.12464142]
Document 37: [1.7241882e+01 4.1971674e+00 3.9339264e+02 3.3836967e-01 4.1722174e+00
 6.0559334e+01 1.8141873e+00 5.4630365e+00 2.6429129e+02 8.2675114e+00]
Document 38: [2.1265450e+01 3.9422840e+01 2.1975740e+02 1.3216007e+01 3.1942166e+02
 1.8599457e+01 2.4285500e+01 7.9905655e+01 7.0190704e-01 1.2480445e-01]
Document 39: [ 48.653355   187.87436     97.53679      0.29644617  86.062775
  33.395744    77.97263     62.409363     9.554421     8.976525  ]
Document 40: [113.301254    65.10637     91.13235      0.2857546    0.927063
  80.23328      2.966986     2.9907582    6.7483335    0.12467578]
Document 41: [ 19.212395   111.971245    99.57125     39.57369     15.475639
   3.5618885   27.737848    93.33711      9.233543     0.12472266]
Document 42: [ 1.6280051   7.155014   21.078424    3.4392242  21.28682    11.263313
  4.5326157  15.914974    0.45014596  0.12464377]
Document 43: [11.875963  43.858337  74.74724   16.339985  38.12518   26.491743
  8.377709  61.270615   0.6181754  0.1248832]
Document 44: [ 11.682531   38.50609   101.72709    15.619553   40.96164     9.561077
  26.44075    12.853673    0.5125001   1.9706476]
Document 45: [1.92756882e+02 4.32294273e+01 1.24708656e+02 4.41543627e+00
 7.18328619e+00 9.33856201e+01 3.85242195e+01 1.83115995e+00
 4.55872421e+01 1.24739096e-01]
Document 46: [ 27.94004    153.75734    132.01929      0.31079346  60.45846
   4.5139728   31.106138   101.85512      1.519763     2.2381878 ]
Document 47: [ 38.032463   36.84141   116.820724   17.079462   79.039215   18.405535
  82.63951     5.2062798  24.60292     0.1246198]
Document 48: [13.61674   28.922709  73.46662    0.3329992 15.013825  76.336136
  3.0392933 47.703438   5.504002   1.9004295]
Document 49: [ 38.29131    122.57989     79.287506     0.29103005  38.024815
   9.771682    35.801548    23.986568    37.579063     0.12469825]
Document 50: [ 3.6718597  18.341673   15.288208   31.690952   21.822083   29.224987
  1.9909105  23.992676    1.725632    0.12464105]
Document 51: [12.634788    9.86553    24.06396     0.29776508  1.1584212  39.67109
  7.101516    0.83036965 24.137346    0.12496924]
Document 52: [ 4.4473658  26.975779   10.360274    0.2805023   5.6499133  18.271154
  1.1538799   2.971424    0.6431576   0.12476761]
Document 53: [47.976143   44.85206    31.87178     0.3045035   2.6174455  31.907026
 20.394512    8.560201   11.232654    0.12469818]
Document 54: [ 9.451367    5.9505014  16.508574    0.29244503 10.346329   25.703964
 14.175804    3.098113    6.104708    5.253079  ]
Document 55: [ 3.4353082  8.284494  22.486149  18.1166     5.3484464  5.5391803
 23.011396   0.8050707  3.192325   1.6714276]
Document 56: [2.0193142e+01 2.1689806e+02 1.3188979e+02 5.3989720e+00 1.5110854e+01
 3.0024529e+01 2.6305119e+01 2.6230289e+01 1.3590610e+01 1.2466876e-01]
Document 57: [2.8569853e+00 1.8795187e+00 2.0730241e+02 2.8986794e-01 1.1238384e+00
 4.7208123e+00 4.5947275e+02 1.1147518e+00 6.3845509e+01 1.2479710e-01]
Document 58: [  3.1528492    1.7908154  200.2079       0.96880955   1.7738142
  18.572624   402.7374       0.8458431   22.032581     8.620532  ]
Document 59: [1.78185654e+00 5.41830778e+00 5.05358490e+02 3.05756420e-01
 3.95541096e+00 6.73291540e+00 2.13493862e+01 2.74380684e+00
 1.19023315e+02 9.11545181e+00]
Document 60: [175.34912      3.1211987   49.657112     0.2793332    0.91160154
   1.2395409    5.641554     0.7076882   13.563872   149.36372   ]
Document 61: [3.7006228e+00 3.1054684e+01 2.2051820e+02 1.3710152e+02 5.3834335e+01
 8.3462029e+00 1.1470152e+02 1.3670874e+00 4.4963196e+01 1.2487996e-01]
Document 62: [4.2486046e+01 3.1893572e+01 5.6477533e+02 2.8359579e+01 5.5552120e+01
 9.3059759e+00 7.7327759e+01 1.7104506e+00 2.6061304e+01 1.2474180e-01]
Document 63: [3.46534546e+02 4.64809761e+01 4.60172760e+02 1.07765865e+01
 1.58017302e+00 3.03805256e+00 2.55156631e+01 1.81021976e+01
 2.93371239e+01 1.24650225e-01]
Document 64: [177.5796      23.378422    76.968956     0.29183456   0.95936644
  46.4445       8.747545     1.1054358   30.117256     4.2370625 ]
Document 65: [ 15.572801    15.041067   116.32371      5.4018145    5.2861137
  85.89711      2.301146    84.94697      3.9203606    0.12465189]
Document 66: [ 28.486176    5.9204006 127.58621    49.849674   18.36494    21.164433
   8.045208  432.4326      8.278436    1.5358377]
Document 67: [6.15422344e+00 1.80643392e+00 2.17642822e+02 1.32687235e+01
 3.10305715e+00 7.31874275e+00 1.13361335e+00 8.45085025e-01
 4.68709946e-01 1.24688968e-01]
Document 68: [1.6822265e+00 1.4416214e+00 1.0172714e+02 2.9968333e-01 2.1192047e+01
 1.2412532e+03 1.7682726e+00 1.4849287e+02 5.6958985e-01 1.2475633e-01]
Document 69: [ 52.913136    21.075897    87.04075      0.31067258 213.45724
  30.1317      10.806139    18.30713      0.61866647  36.08541   ]
Document 70: [ 13.607729  248.49838   203.7058     11.143842   52.732487   80.00069
 108.2006    169.35065    43.49301     3.8921053]
Document 71: [5.0449413e+01 1.1631276e+02 8.9158997e+01 1.2838399e+02 3.7444920e+01
 2.2702175e+01 6.0639847e+01 6.6336586e+01 1.2162014e+01 1.2473706e-01]
Document 72: [1.6134903e+01 4.7996960e+01 2.8899035e+01 2.8887066e-01 3.7757557e+01
 2.2772129e+01 4.9127811e+02 2.9591365e+00 5.3051049e-01 1.2465589e-01]
Document 73: [ 62.494835   88.28905   165.46048     4.371202   85.07687    51.743706
  50.560535   22.951286   32.60439     5.1974697]
Document 74: [3.0832062e+02 8.1884468e+01 1.0354188e+02 2.1575060e+01 8.4921017e+00
 4.0261528e+01 1.2159582e+01 1.0098883e+01 2.1321414e+02 1.2472693e-01]
Document 75: [ 59.247044  414.53445    98.02523     3.5441175  15.035627   15.985252
  91.11659   202.89009     1.2654793  15.920501 ]
Document 76: [6.3878490e+01 7.3679886e+01 2.0942375e+02 1.3553114e+00 7.5029944e+02
 2.4974260e+00 1.6488640e+01 1.0154019e+01 5.8205563e-01 1.2474206e-01]
Document 77: [2.5077854e+01 2.1252800e+02 1.2760422e+02 1.8998528e+01 1.6734229e+02
 4.0012770e+00 2.2188823e+02 1.6347577e+02 5.6141067e-01 1.2466165e-01]
Document 78: [1.9423270e+02 8.5170128e+01 9.8475548e+01 2.8408185e-01 6.8567963e+00
 6.5401093e+01 4.2111809e+01 1.5557480e+01 1.7852022e+02 1.2479128e-01]
Document 79: [1.1160102e+02 1.2768418e+02 2.2867426e+02 2.9302871e-01 4.9574623e+01
 4.8670135e+01 7.9444809e+01 5.4467388e+01 4.7186501e+01 1.2486131e-01]
Document 80: [  6.5725994  12.786869   69.539375   11.686132   16.824135  130.97264
  35.748203   23.42615     1.9361627   5.329382 ]
Document 81: [172.47055     31.605932   148.33893      0.28544188  22.579628
  19.925972    25.674974    21.63376     63.69839     90.5311    ]
Document 82: [ 76.04382     96.34094     22.927547     0.28546232   6.525292
 109.530304    51.794037     9.147806     8.082956     0.12474951]
Document 83: [ 10.697117   21.346632   70.09669     7.950219   16.412113  158.86589
   4.490076   21.779875    1.9063361   2.271227 ]
Document 84: [ 20.162415  106.65643   198.14795    12.371647  362.52896     1.6770468
  28.42032   216.85895    10.546312   10.24453  ]
Document 85: [9.6058746e+01 5.9391357e+01 2.4633890e+02 7.8750515e+00 5.6002426e+01
 9.0122252e+00 4.4458824e+01 1.8443761e+00 6.9192392e-01 1.2465654e-01]
Document 86: [1.9569138e+01 5.4779854e+01 7.0685631e+01 2.9033950e-01 2.1089249e+02
 7.6783937e-01 1.2237316e+00 5.7727867e+01 3.7195208e+00 1.2489919e-01]
Document 87: [1.21966715e+01 9.27278061e+01 1.31829102e+02 1.88029495e+02
 1.88032608e+02 9.11008000e-01 1.70219555e+01 7.74309826e+00
 2.13148069e+00 1.24708079e-01]
Document 88: [ 31.886639    24.694578    70.07578     43.667645   117.16857
   1.4793372   10.345922    12.909868     0.4599536    0.12465897]
Document 89: [180.70502    29.323017   39.669098    4.322415   68.9605      8.4271965
  37.65734    16.071196    7.8181357 295.72723  ]
Document 90: [1.57757309e+02 5.45648804e+01 9.39572430e+00 3.10404092e-01
 2.30031281e+01 7.36549950e+00 5.79392883e+02 3.35483170e+01
 1.11156250e+02 1.24625415e-01]
Document 91: [ 8.254359 34.157322 43.8579   29.445612 37.64362  12.031153 33.68848
 47.253456 42.267357 21.225204]
Document 92: [9.03855133e+00 5.91095448e+00 1.02832384e+01 2.89707959e-01
 7.16431961e+01 4.68060760e+01 1.27366281e+00 1.49522995e+02
 6.95878458e+00 1.24656126e-01]
Document 93: [2.55134521e+02 1.50392711e+00 4.98328400e+00 8.32118130e+00
 1.56530485e+01 4.76879406e+00 1.05989790e+00 8.54470670e-01
 4.59694445e-01 1.24619760e-01]
Document 94: [2.6353912e+01 2.4140198e+00 8.8517395e+01 5.4922009e+01 4.6194553e+01
 8.7346970e+01 7.9809337e+00 4.1439450e+02 4.1473415e+01 1.2483778e-01]
Document 95: [  2.0878344   45.42847     84.48966    122.74238     21.924187
   4.2761536    5.2139926   16.064018     0.46189156   0.12476606]
Document 96: [ 3.4242084   8.7595     73.22024     0.28720123 37.36057    12.045883
  4.239195   98.93412     0.5578915  12.031425  ]
Document 97: [  7.6502275   15.179784    55.806858   113.69805     63.798893
   7.386399     2.4429028   44.013203     0.69378567   0.12464903]
Document 98: [6.15421247e+00 1.80643106e+00 2.17642136e+02 1.32691565e+01
 3.10181952e+00 7.32023335e+00 1.13361502e+00 8.45086932e-01
 4.68710005e-01 1.24688976e-01]
Document 99: [1.7818565e+00 5.4183049e+00 5.0535834e+02 3.0575642e-01 3.9554129e+00
 6.7329102e+00 2.1349392e+01 2.7438076e+00 1.1902317e+02 9.1157551e+00]
Document 100: [1.6822246e+00 1.4416219e+00 1.0172700e+02 2.9968330e-01 2.1192593e+01
 1.2412534e+03 1.7680763e+00 1.4849281e+02 5.6932712e-01 1.2475633e-01]
Document 101: [6.3878498e+01 7.3679825e+01 2.0942369e+02 1.3556082e+00 7.5029926e+02
 2.4974260e+00 1.6488636e+01 1.0154023e+01 5.8205563e-01 1.2474206e-01]
Document 102: [64.772      30.241411   46.505344    3.7381077   1.3868717  38.86991
  1.3442252  10.344094   78.52541     0.12473413]
Document 103: [16.549734   9.510112  83.79443   15.488344  57.002193   4.8423033
  5.1681213 17.736897   0.9781613  2.779604 ]
Document 104: [5.2716475e+00 4.0814060e+01 1.8106079e+02 6.2344223e+01 1.1099032e+02
 8.7901316e+00 2.1742031e+01 1.3965584e+01 1.6534278e+00 1.2465565e-01]
Document 105: [17.480236  33.484657  57.989716   0.3158867 45.456      1.566775
 14.676926  21.763128   8.471332   1.6344486]
Document 106: [ 51.57833    119.05169     78.9521      10.755978   212.73155
  12.068396     4.209057    99.76189      0.53649074  18.05721   ]
Document 107: [589.36993  206.36658  361.75552   19.432657 463.3804    14.37872
  50.428467  98.165504   4.643208 130.25108 ]
Document 108: [ 14.487281  218.73602   101.48106   478.83005   131.60983    27.958899
   9.349733    5.702468    0.4791031  17.956518 ]
Document 109: [17.295776  31.623848  49.144924   6.2549973 60.389187   4.451773
 11.540569  14.596631   0.4629199  8.069647 ]
Document 110: [23.48198   27.302366  71.87197    6.39032   76.26349    2.53221
  5.17876    9.742942   1.4471714  2.6352208]
Document 111: [11.233049   20.388302   43.507816    9.615827   50.294243    1.9782366
  5.0166397  14.223172    0.4821573   0.12468516]
Document 112: [46.600147   54.976753   73.16924     0.2838475  65.001366    2.0375829
  9.671701    0.9066882  81.05913     0.12465797]
Document 113: [23.43422    41.781124   32.46576     0.27834192 15.926659    1.7547891
 29.715878   72.5936     31.772976    0.12462974]
Document 114: [ 2.4533825  13.849529   47.796116   14.998778   61.012825    0.6266469
  6.6040406  15.917897    0.46167246  0.1246923 ]
Document 115: [ 2.38647     3.7454453  26.120668    0.27950227  9.224607    1.2771046
  2.9958808  15.249295    0.4903766   0.12481091]
Document 116: [3.15575600e+01 4.48026314e+01 1.45335144e+02 5.54705667e+00
 1.05254585e+02 6.64402246e+00 6.18457937e+00 3.84343987e+01
 1.87150478e+00 1.24771193e-01]
Document 117: [ 18.823395   25.662418   62.448227   11.938579  113.9883      2.5525534
   1.4637508  35.807476    0.4697934   9.653528 ]
Document 118: [2.1265377e+01 3.9422806e+01 2.1975737e+02 1.3216017e+01 3.1942169e+02
 1.8599434e+01 2.4285458e+01 7.9905663e+01 7.0204687e-01 1.2480445e-01]
Document 119: [16.49524    37.370758   74.70488    48.06724    90.76539     4.534896
 13.616051   42.894012    6.2253847   0.12475119]
Document 120: [20.216167   63.912914   81.35078    57.970562   51.613667   12.765197
 12.096212   95.218895    0.47158703  0.12465371]
Document 121: [17.991154  53.950455  50.9627    22.707481   1.3876786  0.6258984
  8.3310795 27.466194   0.6955775  7.7319   ]
Document 122: [8.81373692e+00 1.04543091e+02 1.43999634e+02 9.93422775e+01
 4.02579994e+01 7.60017991e-01 1.39336128e+01 1.96343307e+01
 2.34491730e+00 1.24665886e-01]
Document 123: [27.817429   51.201263   40.134377   61.92507    30.70084     3.9991455
 22.964645   11.335319    0.55723643  7.1811986 ]
Document 124: [ 8.847262   28.20604    47.617104    0.31283548 61.163074    0.72574353
  6.305279   25.086206    0.4709065   0.12472643]
Document 125: [ 20.482658    27.04004    103.15038      6.241492    77.905426
  12.3959255   15.047173    31.839949     0.5861778    0.12465018]
Document 126: [ 85.68615    195.04398    210.14763      0.28333664 146.92918
  24.693068    17.935843    31.839806     2.7261076  129.39044   ]
Document 127: [64.77203    30.24152    46.50553     3.738032    1.3866324  38.86996
  1.3441294  10.344118   78.52542     0.12473413]
Document 128: [25.665886   24.134598   74.08385    80.72637    45.0668      0.9887154
 13.70862    16.950808    2.3711963   0.12467302]
Document 129: [  4.6038265  47.64633   106.47313   138.79907   113.74614     5.670301
   5.9922233  63.537308    0.954861    4.358491 ]
Document 130: [1.2410405e+01 6.5005875e+01 2.2578621e+02 2.7321424e+01 3.7688515e+01
 8.8496590e-01 1.0884115e+01 8.6182205e+01 4.7496086e-01 1.2470584e-01]
Document 131: [ 9.204628   25.273365   48.61355    24.869894   69.18042     1.3870671
  9.648148    9.671833    0.48533982  6.508159  ]
Document 132: [15.407633   16.667227   23.11871     0.28406683  3.4660618  16.309624
 13.310242    0.6592075  73.527855    0.12463057]
Document 133: [  4.2042217   46.923546   102.30975     53.64893     87.60591
   1.3928614   15.685957    76.28836      0.5887312    0.12486096]
Document 134: [14.830417  13.980654  38.981026   3.0376513 58.800587   3.0510356
  1.8407042 20.841295   1.5920191  6.9076924]
Document 135: [ 16.639446  113.492325  158.18323    61.158325  131.93144     6.1272984
  32.46944    72.04758    42.616352    3.052482 ]
Document 136: [ 5.478726   20.372725   58.210308    8.258156   31.78099    11.09057
  4.0177884   5.6160116  11.918571    0.12471566]
Document 137: [1.7818565e+00 5.4183083e+00 5.0535858e+02 3.0575639e-01 3.9554100e+00
 6.7329202e+00 2.1349373e+01 2.7438052e+00 1.1902343e+02 9.1152267e+00]
Document 138: [175.34904      3.1211941   49.65713      0.27933323   0.9116019
   1.2406135    5.6412077    0.70768964  13.563298   149.36363   ]
Document 139: [3.7005517e+00 3.1054665e+01 2.2051842e+02 1.3710156e+02 5.3834637e+01

In [26]:
# Display topics identified by LDA model
topics = lda_model.print_topics()
for topic in topics:
    print(topic)

(0, '0.040*"function" + 0.024*"neuron" + 0.021*"value" + 0.018*"gradient" + 0.017*"loss" + 0.011*"output" + 0.011*"vector" + 0.010*"sigmoid" + 0.010*"table" + 0.009*"zero"')
(1, '0.014*"architecture" + 0.013*"performance" + 0.010*"test" + 0.010*"provide" + 0.009*"compute" + 0.009*"run" + 0.009*"perform" + 0.009*"improve" + 0.008*"power" + 0.008*"similar"')
(2, '0.012*"word" + 0.011*"memory" + 0.009*"say" + 0.009*"google" + 0.008*"generate" + 0.008*"brain" + 0.007*"text" + 0.007*"language" + 0.007*"article" + 0.007*"turn"')
(3, '0.026*"say" + 0.025*"bots" + 0.024*"message" + 0.022*"sound" + 0.019*"chatbots" + 0.017*"user" + 0.017*"chatbot" + 0.017*"felt" + 0.014*"person" + 0.013*"users"')
(4, '0.023*"intelligence" + 0.021*"artificial" + 0.017*"systems" + 0.017*"technology" + 0.012*"company" + 0.011*"years" + 0.010*"field" + 0.010*"research" + 0.010*"software" + 0.010*"future"')
(5, '0.034*"course" + 0.030*"python" + 0.028*"https" + 0.020*"blog" + 0.018*"program" + 0.018*"keras" + 0.017*"github" + 0.017*"cluster" + 0.016*"numpy" + 0.013*"science"')
(6, '0.089*"image" + 0.035*"feature" + 0.023*"object" + 0.016*"size" + 0.013*"card" + 0.012*"layer" + 0.012*"convolutional" + 0.012*"parameters" + 0.011*"face" + 0.011*"accuracy"')
(7, '0.020*"gpus" + 0.016*"experience" + 0.011*"important" + 0.011*"spend" + 0.010*"title" + 0.010*"have" + 0.010*"question" + 0.009*"offer" + 0.009*"product" + 0.009*"online"')
(8, '0.086*"layer" + 0.084*"weight" + 0.041*"output" + 0.040*"neurons" + 0.037*"code" + 0.025*"activation" + 0.024*"function" + 0.023*"tensorflow" + 0.021*"line" + 0.020*"dataset"')
(9, '0.095*"action" + 0.053*"game" + 0.047*"reinforcement" + 0.045*"state" + 0.043*"policy" + 0.041*"value" + 0.040*"environment" + 0.039*"reward" + 0.036*"agent" + 0.026*"update"')

In [27]:
# Alternatively, use show_topics, which gives more options
topics = lda_model.show_topics(num_topics=5, num_words=5, formatted=False)
for topic in topics:
    print(topic)

(9, [('action', 0.09506562), ('game', 0.05293879), ('reinforcement', 0.046531457), ('state', 0.045139953), ('policy', 0.042585287)])
(3, [('say', 0.025678363), ('bots', 0.025151536), ('message', 0.024490038), ('sound', 0.022419864), ('chatbots', 0.019159501)])
(1, [('architecture', 0.014061382), ('performance', 0.012969055), ('test', 0.010217222), ('provide', 0.009984964), ('compute', 0.009482685)])
(0, [('function', 0.03959323), ('neuron', 0.023712989), ('value', 0.020831168), ('gradient', 0.018119125), ('loss', 0.017020198)])
(2, [('word', 0.011774831), ('memory', 0.01081743), ('say', 0.009354277), ('google', 0.008912241), ('generate', 0.008229118)])

In [28]:
# Create Topic Distance Visualization
pyLDAvis.enable_notebook()
pyLDAvis.gensim.prepare(lda_model, bow_corpus, dictionary)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2      0.040412 -0.120814       1        1  23.658050
4      0.189940  0.097741       2        1  13.503945
0     -0.154160  0.146854       3        1  12.449466
1     -0.018036  0.264722       4        1  11.358462
6     -0.171687  0.074517       5        1  10.712311
7      0.111053 -0.153142       6        1   8.526427
5      0.006936 -0.244534       7        1   7.548246
8     -0.281569 -0.107960       8        1   5.176954
3      0.251457  0.060833       9        1   4.232831
9      0.025655 -0.018216      10        1   2.833309, topic_info=           Term         Freq        Total Category  logprob  loglift
846       image  1617.000000  1617.000000  Default  30.0000  30.0000
211       layer  1123.000000  1123.000000  Default  29.0000  29.0000
776      weight   843.000000   843.000000  Default  28.0000  28.0000
450    function  1067.000000  1067.000000  Default  27.0000  27.0000
546      action   459.000000   459.000000  Default  26.0000  26.0000
..          ...          ...          ...      ...      ...      ...
285     provide    59.086208   397.128512  Topic10  -4.4021   1.6585
684  algorithms    51.916313   348.510857  Topic10  -4.5315   1.6597
126      expect    40.346722   200.539142  Topic10  -4.7836   1.9602
563      choose    42.042137   246.367458  Topic10  -4.7425   1.7956
502     science    40.438775   423.524319  Topic10  -4.7813   1.2149

[578 rows x 6 columns], token_table=      Topic      Freq      Term
term
1296      4  0.188907  accuracy
1296      5  0.809013  accuracy
2         1  0.211133   achieve
2         2  0.015449   achieve
2         3  0.041197   achieve
...     ...       ...       ...
404       5  0.185151     years
404       6  0.087571     years
543       7  0.978753   youtube
778       1  0.082251      zero
778       3  0.913902      zero

[1097 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[3, 5, 1, 2, 7, 8, 6, 9, 4, 10])