# [9665] Exercise : Sklearn (multi-model) - Solution
Data file: https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9665/main/data/breast_cancer_diagnosis.csv

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 01/27/25 19:23:39

### Import libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

### Load data

In [3]:
# Read data from file (breast_cancer_diagnosis.csv) into dataframe
df = pd.read_csv('https://raw.githubusercontent.com/vjavaly/Baruch-CIS-9665/main/data/breast_cancer_diagnosis.csv')

### Examine data

In [4]:
# Review dataframe shape
df.shape

(569, 13)

In [5]:
# Display first few rows of dataframe
df.head()

,id,name,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age,diagnosis
0,ID842302,Glynnis Munson,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35,1
1,ID842517,Lana Behrer,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27,1
2,ID84300903,Devondra Vanvalkenburgh,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31,1
3,ID84348301,Glory Maravalle,NaN,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49,1
4,ID84358402,Mellie Mccurdy,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20,1

Note: NaN in radius column

### Prepare data

#### Drop "meaningless" variables
Remember to use "inplace=True"

In [6]:
df.drop(["id", "name"], axis=1, inplace=True)

In [7]:
# Display first few rows of updated dataframe
df.head()

,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age,diagnosis
0,NaN,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35,1
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27,1
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31,1
3,NaN,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49,1
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20,1

#### Check for missing values

In [8]:
df.isnull().sum()

radius               71
texture               0
perimeter             0
area                  0
smoothness            0
compactness           0
concavity             0
symmetry              0
fractal_dimension     0
age                   0
diagnosis             0
dtype: int64

#### Use the SimpleImputer to replace missing values

In [9]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

In [10]:
df = pd.DataFrame(imp_mean.fit_transform(df), columns=df.columns)

In [11]:
# Display first few rows of updated dataframe
df.head()

,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age,diagnosis
0,14.326635,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.2419,0.07871,35.0,1.0
1,20.570000,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.1812,0.05667,27.0,1.0
2,19.690000,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.2069,0.05999,31.0,1.0
3,14.326635,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.2597,0.09744,49.0,1.0
4,20.290000,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.1809,0.05883,20.0,1.0

#### Check for missing values again

In [12]:
df.isnull().sum()

radius               0
texture              0
perimeter            0
area                 0
smoothness           0
compactness          0
concavity            0
symmetry             0
fractal_dimension    0
age                  0
diagnosis            0
dtype: int64

### Separate independent and dependent variables
* Independent variables: All remaining variables except Diagnosis
* Dependent variable: Diagnosis

In [13]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

#### Standardize the data

In [14]:
scaler = StandardScaler()
X[X.columns] = scaler.fit_transform(X[X.columns])
X.head()

,radius,texture,perimeter,area,smoothness,compactness,concavity,symmetry,fractal_dimension,age
0,0.000000,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.217515,2.255747,-0.328668
1,1.904915,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.001392,-0.868652,-0.917218
2,1.636418,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,0.939685,-0.398008,-0.622943
3,0.000000,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,2.867383,4.910919,0.701295
4,1.819484,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,-0.009560,-0.562450,-1.432199

In [15]:
# Display first few rows of dependent variable
y.head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: diagnosis, dtype: float64

### Split data into training and test sets

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

### Train Logistic Regression model

In [17]:
LogReg_model = LogisticRegression()
LogReg_model.fit(X_train, y_train)

LogisticRegression()

### Evaluate Logistic Regression model

In [18]:
LogReg_predictions = LogReg_model.predict(X_test)
LogReg_accuracy = accuracy_score(y_test, LogReg_predictions)
print("Logistic regression accuracy = ", round((LogReg_accuracy * 100), 5), "%")

Logistic regression accuracy =  95.90643 %

### Train Random Forest Classifier model

In [19]:
RF_model = RandomForestClassifier()
RF_model.fit(X_train, y_train)

RandomForestClassifier()

### Evaluate Random Forest Classifier model

In [20]:
RF_predictions = RF_model.predict(X_test)
RF_accuracy = accuracy_score(y_test, RF_predictions)
print("Random forest accuracy = ", round((RF_accuracy * 100), 5), "%")

Random forest accuracy =  97.66082 %

### Train Naive Bayes model

In [21]:
NBG_model = GaussianNB()
NBG_model.fit(X_train, y_train)

GaussianNB()

### Evaluate Naive Bayes model

In [22]:
NBG_predictions = NBG_model.predict(X_test)
NBG_accuracy = accuracy_score(y_test, NBG_predictions)
print("Naive Bayes (Gaussian) accuracy = ", round((NBG_accuracy * 100), 5), "%")

Naive Bayes (Gaussian) accuracy =  92.39766 %

### Train Support Vector Classifier model

In [23]:
SVC_model = SVC()
SVC_model.fit(X_train, y_train)

SVC()

### Evaluate Support Vector Classifier model

In [24]:
SVC_predictions = SVC_model.predict(X_test)
SVC_accuracy = accuracy_score(y_test, SVC_predictions)
print("Support vector machine accuracy = ", round((SVC_accuracy * 100), 5), "%")

Support vector machine accuracy =  97.07602 %