# [9665] Hugging Face 2

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 04/29/25 01:39:24

### Import libraries

In [2]:
%%time

! pip install "huggingface_hub[hf_xet]"

Requirement already satisfied: huggingface_hub[hf_xet] in /usr/local/lib/python3.11/dist-packages (0.30.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_xet]) (4.13.2)
Collecting hf-xet>=0.1.4 (from huggingface_hub[hf_xet])
  Downloading hf_xet-1.0.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (494 bytes)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub[hf_xet]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub[hf_xet]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub[hf_xet]) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub[hf_xet]) (2025.1.31)
Downloading hf_xet-1.0.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (54.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 MB 8.9 MB/s eta 0:00:00
Installing collected packages: hf-xet
Successfully installed hf-xet-1.0.5
CPU times: user 125 ms, sys: 19.9 ms, total: 145 ms
Wall time: 18.4 s

In [3]:
import pandas as pd
from google.colab import userdata
from huggingface_hub import login
from pprint import pprint

In [4]:
%%time

# Hugging Face transformers library's module pipeline
from transformers import pipeline

CPU times: user 14.4 s, sys: 2.08 s, total: 16.5 s
Wall time: 26.4 s

### Connect to Hugging Face

In [5]:
HF_TOKEN = userdata.get('HF_TOKEN')
login(token=HF_TOKEN)

### Text generation

In [6]:
%%time

# Use a publicly available LLM: distilgpt2
generator = pipeline('text-generation', model='distilgpt2')

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu

CPU times: user 3.09 s, sys: 2.19 s, total: 5.29 s
Wall time: 9.13 s

In [7]:
%%time

prompt = "Write a short story about a robot who learns to love."
generated_text = generator(prompt, max_length=750, num_return_sequences=1,
                           truncation=True)[0]['generated_text']
pprint(generated_text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

("Write a short story about a robot who learns to love. I'll use a very basic "
 "approach to understanding how it works, but I haven't got a huge audience "
 'for it.\n'
 '\n'
 '\n'
 'That said, a tiny robot gets a lot of attention on the internet and a lot of '
 "people are writing about that. But I don't have any way of trying to keep it "
 'going. I just plan on using that blog to get some interesting stuff.\n'
 "If you'd like to know what's new at this blog, I'd love to hear from you!\n"
 "For this post, I'm going to be doing my first full disclosure with a blog in "
 'April and maybe a bit earlier. This will be so far, so check out this post '
 "for that and then go talk of what's new in my first blog.\n"
 "It's an open source project, so I'd rather keep this project private. I'm in "
 'great condition and I hope you give some feedback.\n'
 "If this doesn't make you too motivated to come back or stop, you can find me "
 'at www.reddit.com/r/luna or on the forums at http://r/Luna_Luna.')
CPU times: user 8.2 s, sys: 34.6 ms, total: 8.24 s
Wall time: 8.32 s

In [8]:
%%time

prompt = "Explain quantum physics in simple terms."
generated_text = generator(prompt, max_length=200, num_return_sequences=1,
                           truncation=True)[0]['generated_text']
pprint(generated_text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

('Explain quantum physics in simple terms.\n'
 '\n'
 '\n'
 '\n'
 '\n'
 "At least I'm looking forward to this post. You can find me on Pinterest at "
 '@pahdew.')
CPU times: user 1.07 s, sys: 532 µs, total: 1.07 s
Wall time: 1.07 s

In [9]:
%%time

prompt = "What are the benefits of learning python?"
generated_text = generator(prompt, max_length=500, num_return_sequences=1,
                           truncation=True)[0]['generated_text']
pprint(generated_text)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

('What are the benefits of learning python? There are the basics in python and '
 'they are very simple and they are very useful.\n'
 '\n'
 '\n'
 '\n'
 'Learn Python: Python\n'
 'As we move away from the idea of the simple, we now have a very basic '
 'understanding of python. Python makes it possible for us to learn some '
 "interesting things that we all really don't know yet. For example, in our "
 'example we can learn about the Python language. We can learn the language of '
 'Python using standard Python or C with Python.\n'
 'We are using Python (C++) for a basic purpose, and using the Python API to '
 'learn a bit about Python. The Python module is called Python_Py and the '
 'Python interface is called Python_Py which can be seen on the left below.\n'
 'python_py\n'
 'We will now start learning Python and Python as we enter into a new world of '
 'learning.\n'
 'Python is currently the fastest language and so we can learn languages as we '
 'enter into a new world of learning. With Python you can even learn to code '
 'with Python.\n'
 'If you want to learn Python go check out the Wikipedia article "Python from '
 'Python."')
CPU times: user 8.63 s, sys: 19.7 ms, total: 8.65 s
Wall time: 8.71 s

### Sentiment analysis

In [10]:
%%time

# Initialize the sentiment analysis pipeline
sentiment_analyzer = pipeline("sentiment-analysis",
                              model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
                              revision="714eb0f")

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu

CPU times: user 1.38 s, sys: 1.66 s, total: 3.05 s
Wall time: 4.54 s

In [11]:
pd.set_option('display.max_colwidth', None)

In [12]:
# Simple sentences
sa_simple_sentences = [
    "I love this movie! It's so amazing.",
    "The food was terrible, and the service was awful.",
    "This is a neutral statement.",
    "I'm feeling quite happy today.",
    "The news made me incredibly sad.",
    "What a wonderful day!",
    "I have mixed feelings about this.",
    "The product was okay, but not great.",
    "This is the best thing that's ever happened!",
    "I'm so disappointed.",
]

In [13]:
# Perform sentiment analysis
results = sentiment_analyzer(sa_simple_sentences)

# Store results in dataframe
df = pd.DataFrame({
    "sentence": sa_simple_sentences,
    "sentiment": [result["label"] for result in results],
    "score": [result["score"] for result in results],
})

print("Simple sentences results")
df

Simple sentences results

                                            sentence sentiment     score
0                I love this movie! It's so amazing.  POSITIVE  0.999884
1  The food was terrible, and the service was awful.  NEGATIVE  0.999741
2                       This is a neutral statement.  NEGATIVE  0.837159
3                     I'm feeling quite happy today.  POSITIVE  0.999887
4                   The news made me incredibly sad.  NEGATIVE  0.996988
5                              What a wonderful day!  POSITIVE  0.999881
6                  I have mixed feelings about this.  NEGATIVE  0.990378
7               The product was okay, but not great.  NEGATIVE  0.997779
8       This is the best thing that's ever happened!  POSITIVE  0.999790
9                               I'm so disappointed.  NEGATIVE  0.999758

In [14]:
# More Complex Examples
sa_complex_sentences = [
    "Despite the initial setbacks, the team managed to pull through and deliver an outstanding performance.",
    "While the concept is intriguing, the execution leaves much to be desired.",
    "The sheer brilliance of the artwork was only slightly marred by the poor lighting.",
    "Although the movie had its moments, the overall plot felt rather convoluted.",
    "Even though the weather was dreadful, the atmosphere at the concert was electric.",
]

In [15]:
# Perform sentiment analysis
complex_results = sentiment_analyzer(sa_complex_sentences)

# Store results in dataframe
complex_df = pd.DataFrame({
    "sentence": sa_complex_sentences,
    "sentiment": [result["label"] for result in complex_results],
    "score": [result["score"] for result in complex_results],
})

print("Complex sentences results")
complex_df

Complex sentences results

,sentence,sentiment,score
0,"Despite the initial setbacks, the team managed to pull through and deliver an outstanding performance.",POSITIVE,0.999850
1,"While the concept is intriguing, the execution leaves much to be desired.",NEGATIVE,0.996213
2,The sheer brilliance of the artwork was only slightly marred by the poor lighting.,NEGATIVE,0.997708
3,"Although the movie had its moments, the overall plot felt rather convoluted.",NEGATIVE,0.999593
4,"Even though the weather was dreadful, the atmosphere at the concert was electric.",POSITIVE,0.998861

### Named entity recognition (NER)

In [16]:
%%time

# Initialize the NER pipeline
ner_recognizer = pipeline("ner",
                          model='dslim/bert-base-NER')

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu

CPU times: user 981 ms, sys: 790 ms, total: 1.77 s
Wall time: 4.36 s

In [17]:
# Example simple sentences for NER
ner_simple_sentences = [
    "Apple Inc. is headquartered in Cupertino, California.",
    "Barack Obama was the 44th president of the United States.",
    "I'm going to visit the Eiffel Tower in Paris next week.",
    "Google was founded by Larry Page and Sergey Brin.",
    "The Mona Lisa is displayed at the Louvre Museum in France.",
    "Angela Merkel served as the Chancellor of Germany.",
    "Amazon's headquarters are located in Seattle, Washington.",
    "The movie 'The Godfather' was directed by Francis Ford Coppola.",
    "Mount Everest is the highest mountain in the world.",
    "Leonardo da Vinci was a famous Italian artist.",
]

In [18]:
# Perform NER
results = ner_recognizer(ner_simple_sentences)

In [19]:
# Store results in dataframe
data = []
for sentence, result in zip(ner_simple_sentences, results):
    entities = []
    for entity in result:
        entities.append({
            "entity": entity["entity"],
            "word": entity["word"],
            "start": entity["start"],
            "end": entity["end"],
            "score": entity["score"]
            })
    data.append({"sentence": sentence, "entities": entities})

df = pd.DataFrame(data)

print("NER simple results")
df

NER simple results

,sentence,entities
0,"Apple Inc. is headquartered in Cupertino, California.","[{'entity': 'B-ORG', 'word': 'Apple', 'start': 0, 'end': 5, 'score': 0.9994836}, {'entity': 'I-ORG', 'word': 'Inc', 'start': 6, 'end': 9, 'score': 0.99940825}, {'entity': 'B-LOC', 'word': 'Cup', 'start': 31, 'end': 34, 'score': 0.9986935}, {'entity': 'I-LOC', 'word': '##ert', 'start': 34, 'end': 37, 'score': 0.9963397}, {'entity': 'I-LOC', 'word': '##ino', 'start': 37, 'end': 40, 'score': 0.9991534}, {'entity': 'B-LOC', 'word': 'California', 'start': 42, 'end': 52, 'score': 0.99932134}]"
1,Barack Obama was the 44th president of the United States.,"[{'entity': 'B-PER', 'word': 'Barack', 'start': 0, 'end': 6, 'score': 0.99954945}, {'entity': 'I-PER', 'word': 'Obama', 'start': 7, 'end': 12, 'score': 0.99952054}, {'entity': 'B-LOC', 'word': 'United', 'start': 43, 'end': 49, 'score': 0.99972564}, {'entity': 'I-LOC', 'word': 'States', 'start': 50, 'end': 56, 'score': 0.9993253}]"
2,I'm going to visit the Eiffel Tower in Paris next week.,"[{'entity': 'B-LOC', 'word': 'E', 'start': 23, 'end': 24, 'score': 0.9943283}, {'entity': 'I-LOC', 'word': '##iff', 'start': 24, 'end': 27, 'score': 0.599122}, {'entity': 'B-LOC', 'word': '##el', 'start': 27, 'end': 29, 'score': 0.50343853}, {'entity': 'I-LOC', 'word': 'Tower', 'start': 30, 'end': 35, 'score': 0.99388075}, {'entity': 'B-LOC', 'word': 'Paris', 'start': 39, 'end': 44, 'score': 0.9997552}]"
3,Google was founded by Larry Page and Sergey Brin.,"[{'entity': 'B-ORG', 'word': 'Google', 'start': 0, 'end': 6, 'score': 0.9985071}, {'entity': 'B-PER', 'word': 'Larry', 'start': 22, 'end': 27, 'score': 0.99977833}, {'entity': 'I-PER', 'word': 'Page', 'start': 28, 'end': 32, 'score': 0.99972326}, {'entity': 'B-PER', 'word': 'Sergey', 'start': 37, 'end': 43, 'score': 0.9997849}, {'entity': 'I-PER', 'word': 'B', 'start': 44, 'end': 45, 'score': 0.9997067}, {'entity': 'I-PER', 'word': '##rin', 'start': 45, 'end': 48, 'score': 0.99559844}]"
4,The Mona Lisa is displayed at the Louvre Museum in France.,"[{'entity': 'B-MISC', 'word': 'Mona', 'start': 4, 'end': 8, 'score': 0.98897654}, {'entity': 'I-MISC', 'word': 'Lisa', 'start': 9, 'end': 13, 'score': 0.9931979}, {'entity': 'B-LOC', 'word': 'Lou', 'start': 34, 'end': 37, 'score': 0.9632316}, {'entity': 'B-LOC', 'word': '##vre', 'start': 37, 'end': 40, 'score': 0.9881121}, {'entity': 'I-LOC', 'word': 'Museum', 'start': 41, 'end': 47, 'score': 0.9907122}, {'entity': 'B-LOC', 'word': 'France', 'start': 51, 'end': 57, 'score': 0.9996798}]"
5,Angela Merkel served as the Chancellor of Germany.,"[{'entity': 'B-PER', 'word': 'Angela', 'start': 0, 'end': 6, 'score': 0.9998129}, {'entity': 'I-PER', 'word': 'Me', 'start': 7, 'end': 9, 'score': 0.9997609}, {'entity': 'I-PER', 'word': '##rk', 'start': 9, 'end': 11, 'score': 0.99823785}, {'entity': 'I-PER', 'word': '##el', 'start': 11, 'end': 13, 'score': 0.99688244}, {'entity': 'B-LOC', 'word': 'Germany', 'start': 42, 'end': 49, 'score': 0.9996395}]"
6,"Amazon's headquarters are located in Seattle, Washington.","[{'entity': 'B-ORG', 'word': 'Amazon', 'start': 0, 'end': 6, 'score': 0.99908006}, {'entity': 'B-LOC', 'word': 'Seattle', 'start': 37, 'end': 44, 'score': 0.99782723}, {'entity': 'B-LOC', 'word': 'Washington', 'start': 46, 'end': 56, 'score': 0.99854255}]"
7,The movie 'The Godfather' was directed by Francis Ford Coppola.,"[{'entity': 'B-MISC', 'word': 'The', 'start': 11, 'end': 14, 'score': 0.99184495}, {'entity': 'I-MISC', 'word': 'God', 'start': 15, 'end': 18, 'score': 0.96336657}, {'entity': 'I-MISC', 'word': '##father', 'start': 18, 'end': 24, 'score': 0.993048}, {'entity': 'B-PER', 'word': 'Francis', 'start': 42, 'end': 49, 'score': 0.9996593}, {'entity': 'I-PER', 'word': 'Ford', 'start': 50, 'end': 54, 'score': 0.9989747}, {'entity': 'I-PER', 'word': 'Co', 'start': 55, 'end': 57, 'score': 0.99956554}, {'entity': 'I-PER', 'word': '##pp', 'start': 57, 'end': 59, 'score': 0.9974139}, {'entity': 'I-PER', 'word': '##ola', 'start': 59, 'end': 62, 'score': 0.93000317}]"
8,Mount Everest is the highest mountain in the world.,"[{'entity': 'B-LOC', 'word': 'Mount', 'start': 0, 'end': 5, 'score': 0.9046761}, {'entity': 'I-LOC', 'word': 'Everest', 'start': 6, 'end': 13, 'score': 0.5344534}]"
9,Leonardo da Vinci was a famous Italian artist.,"[{'entity': 'B-PER', 'word': 'Leonardo', 'start': 0, 'end': 8, 'score': 0.99945}, {'entity': 'I-PER', 'word': 'da', 'start': 9, 'end': 11, 'score': 0.9983821}, {'entity': 'I-PER', 'word': 'Vinci', 'start': 12, 'end': 17, 'score': 0.9962585}, {'entity': 'B-MISC', 'word': 'Italian', 'start': 31, 'end': 38, 'score': 0.99967706}]"

In [20]:
# More complex sentences for NER
ner_complex_sentences = [
    "On July 20, 1969, Neil Armstrong and Buzz Aldrin became the first humans to land on the moon.",
    "The company announced a new partnership with IBM at the Consumer Electronics Show in Las Vegas.",
    "During World War II, Winston Churchill served as the Prime Minister of the United Kingdom.",
    "The painting 'Starry Night' by Vincent van Gogh is a masterpiece of post-impressionism.",
    "The Olympic Games were held in Tokyo, Japan, in 2021, after a year's delay due to the COVID-19 pandemic.",
]

In [21]:
# Perform NER
results = ner_recognizer(ner_complex_sentences)

In [22]:
# Store results in dataframe
data = []
for sentence, result in zip(ner_complex_sentences, results):
    entities = []
    for entity in result:
        entities.append({
            "entity": entity["entity"],
            "word": entity["word"],
            "start": entity["start"],
            "end": entity["end"],
            "score": entity["score"]
            })
    data.append({"sentence": sentence, "entities": entities})

df = pd.DataFrame(data)

print("NER complex results")
df

NER complex results

,sentence,entities
0,"On July 20, 1969, Neil Armstrong and Buzz Aldrin became the first humans to land on the moon.","[{'entity': 'B-PER', 'word': 'Neil', 'start': 18, 'end': 22, 'score': 0.9997253}, {'entity': 'I-PER', 'word': 'Armstrong', 'start': 23, 'end': 32, 'score': 0.9997181}, {'entity': 'B-PER', 'word': 'Buzz', 'start': 37, 'end': 41, 'score': 0.99974555}, {'entity': 'I-PER', 'word': 'Al', 'start': 42, 'end': 44, 'score': 0.9996939}, {'entity': 'I-PER', 'word': '##dr', 'start': 44, 'end': 46, 'score': 0.99952674}, {'entity': 'I-PER', 'word': '##in', 'start': 46, 'end': 48, 'score': 0.9504874}]"
1,The company announced a new partnership with IBM at the Consumer Electronics Show in Las Vegas.,"[{'entity': 'B-ORG', 'word': 'IBM', 'start': 45, 'end': 48, 'score': 0.9989761}, {'entity': 'B-MISC', 'word': 'Consumer', 'start': 56, 'end': 64, 'score': 0.9934437}, {'entity': 'I-MISC', 'word': 'Electronics', 'start': 65, 'end': 76, 'score': 0.99605954}, {'entity': 'I-MISC', 'word': 'Show', 'start': 77, 'end': 81, 'score': 0.9978631}, {'entity': 'B-LOC', 'word': 'Las', 'start': 85, 'end': 88, 'score': 0.9990088}, {'entity': 'I-LOC', 'word': 'Vegas', 'start': 89, 'end': 94, 'score': 0.9994024}]"
2,"During World War II, Winston Churchill served as the Prime Minister of the United Kingdom.","[{'entity': 'B-MISC', 'word': 'World', 'start': 7, 'end': 12, 'score': 0.9951762}, {'entity': 'I-MISC', 'word': 'War', 'start': 13, 'end': 16, 'score': 0.9977325}, {'entity': 'I-MISC', 'word': 'II', 'start': 17, 'end': 19, 'score': 0.99779296}, {'entity': 'B-PER', 'word': 'Winston', 'start': 21, 'end': 28, 'score': 0.9994062}, {'entity': 'I-PER', 'word': 'Churchill', 'start': 29, 'end': 38, 'score': 0.99929476}, {'entity': 'B-LOC', 'word': 'United', 'start': 75, 'end': 81, 'score': 0.9996965}, {'entity': 'I-LOC', 'word': 'Kingdom', 'start': 82, 'end': 89, 'score': 0.9990657}]"
3,The painting 'Starry Night' by Vincent van Gogh is a masterpiece of post-impressionism.,"[{'entity': 'B-MISC', 'word': 'Starr', 'start': 14, 'end': 19, 'score': 0.8442321}, {'entity': 'I-MISC', 'word': '##y', 'start': 19, 'end': 20, 'score': 0.9389486}, {'entity': 'I-MISC', 'word': 'Night', 'start': 21, 'end': 26, 'score': 0.90637976}, {'entity': 'B-PER', 'word': 'Vincent', 'start': 31, 'end': 38, 'score': 0.99921834}, {'entity': 'I-PER', 'word': 'van', 'start': 39, 'end': 42, 'score': 0.99893945}, {'entity': 'I-PER', 'word': 'Go', 'start': 43, 'end': 45, 'score': 0.99774975}, {'entity': 'I-PER', 'word': '##gh', 'start': 45, 'end': 47, 'score': 0.9610617}]"
4,"The Olympic Games were held in Tokyo, Japan, in 2021, after a year's delay due to the COVID-19 pandemic.","[{'entity': 'B-MISC', 'word': 'Olympic', 'start': 4, 'end': 11, 'score': 0.99727625}, {'entity': 'I-MISC', 'word': 'Games', 'start': 12, 'end': 17, 'score': 0.9876178}, {'entity': 'B-LOC', 'word': 'Tokyo', 'start': 31, 'end': 36, 'score': 0.9992054}, {'entity': 'B-LOC', 'word': 'Japan', 'start': 38, 'end': 43, 'score': 0.99966013}, {'entity': 'B-MISC', 'word': 'CO', 'start': 86, 'end': 88, 'score': 0.9974948}, {'entity': 'I-MISC', 'word': '19', 'start': 92, 'end': 94, 'score': 0.85057145}]"

### Question Answering

In [23]:
%%time

# Initialize the question answering pipeline with a specific model
question_answerer = pipeline("question-answering",
                             model="distilbert/distilbert-base-cased-distilled-squad")

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Device set to use cpu

CPU times: user 1.43 s, sys: 1.91 s, total: 3.35 s
Wall time: 4.61 s

In [24]:
# Context and questions (simple)
context = """
The Golden State Warriors are an American professional basketball team based in San Francisco.
The Warriors compete in the National Basketball Association (NBA), as a member of the league's
Western Conference Pacific Division. Founded in 1946 in Philadelphia, the Warriors moved to
the San Francisco Bay Area in 1962 and then to San Francisco in 2019. The team plays its home
games at the Chase Center. The Warriors won the 2022 NBA Finals, their seventh NBA championship.
"""

questions = [
    "Where are the Golden State Warriors based?",
    "Which league do the Warriors compete in?",
    "When were the Warriors founded?",
    "Where do the Warriors play their home games?",
    "How many NBA championships have the Warriors won?",
    "What year did the warriors win their last championship?",
]

In [25]:
# Perform question answering
results = []
for question in questions:
    result = question_answerer(question=question, context=context)
    results.append(result)

In [26]:
# Create a Pandas DataFrame for better visualization
df = pd.DataFrame({
    "question": questions,
    "answer": [result["answer"] for result in results],
    "start": [result["start"] for result in results],
    "end": [result["end"] for result in results],
    "score": [result["score"] for result in results],
})

df

,question,answer,start,end,score
0,Where are the Golden State Warriors based?,San Francisco,81,94,0.976116
1,Which league do the Warriors compete in?,National Basketball Association,124,155,0.520298
2,When were the Warriors founded?,1946,239,243,0.988689
3,Where do the Warriors play their home games?,Chase Center,390,402,0.840103
4,How many NBA championships have the Warriors won?,seventh,448,455,0.781604
5,What year did the warriors win their last championship?,2022,425,429,0.975523

In [27]:
# Context and questions (complex)
complex_context = """
The Amazon rainforest, covering much of northwestern Brazil and extending into Colombia, Peru and other South American countries,
is the world’s largest tropical rainforest, famed for its biodiversity. It’s crisscrossed by thousands of rivers, including the powerful
Amazon. The region contains over 3 million species of plants and animals, and 1 million indigenous people.
"""

complex_questions = [
    "Where is the Amazon rainforest primarily located?",
    "What is the Amazon rainforest known for?",
    "How many species of plants and animals are estimated to live in the Amazon?",
    "Who are the original inhabitants of the Amazon rainforest?",
    "What is the name of the largest river that crosses the Amazon?",
]

In [28]:
# Perform question answering
complex_results = []
for question in complex_questions:
    result = question_answerer(question=question, context=complex_context)
    complex_results.append(result)

In [29]:
# Create a Pandas DataFrame for better visualization
complex_df = pd.DataFrame({
    "question": complex_questions,
    "answer": [result["answer"] for result in complex_results],
    "start": [result["start"] for result in complex_results],
    "end": [result["end"] for result in complex_results],
    "score": [result["score"] for result in complex_results],
})

complex_df

,question,answer,start,end,score
0,Where is the Amazon rainforest primarily located?,northwestern Brazil,41,60,0.534688
1,What is the Amazon rainforest known for?,biodiversity,189,201,0.511870
2,How many species of plants and animals are estimated to live in the Amazon?,3 million,301,310,0.530214
3,Who are the original inhabitants of the Amazon rainforest?,1 million indigenous people,346,373,0.431221
4,What is the name of the largest river that crosses the Amazon?,Amazon,268,274,0.987647